### ISSUE TITLE
invalid "plugin" or missing "module" when sending CHART definition

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#11388]
##### Bug report summary

Some of our stock plugins/plugin's modules:
- set invalid "plugin"
- or set invalid "module" 
- or don't set "module"

when sending [CHART](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#chart) definition.

> CHART type.id name title units [family [context [charttype [priority [update_every [options [plugin [module]]]]]]]]

Correct "plugin"/"module" needed for accounting plugins usage statistics.

Discovered problems:

| Plugin       | Problem     | Fix |
| ------------ | ----------- | --- |
| [freebsd.plugin](https://github.com/netdata/netdata/tree/master/collectors/freebsd.plugin#freebsdplugin) | sends "plugin" as "freebsd" for the following modules: stats (Netdata Monitoring), zfs  | "freebsd" => "freebsd.plugin" |
| [macos.plugin](https://github.com/netdata/netdata/tree/master/collectors/macos.plugin#macosplugin) | sends "plugin" as "macos" for the following modules: stats (Netdata Monitoring), sysctl, mach_smi, iokit  | "macos" => "macos.plugin" |
| [charts.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/charts.d.plugin#chartsdplugin) | doesn't send "module" | add "module" for all modules charts |
| [node.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin#nodedplugin) | doesn't send "module" | add "module" for all modules charts |
| [ebpf.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/ebpf.plugin#ebpf-monitoring-with-netdata) | doesn't send "module" | add "module" for all modules charts |
| [statsd.plugin](https://github.com/netdata/netdata/tree/master/collectors/statsd.plugin#statsdplugin) | sends path to a config file as "module" for [synthetic charts](https://learn.netdata.cloud/docs/agent/collectors/statsd.plugin#synthetic-statsd-charts) | [path to the config => "synthetic_chart"](https://github.com/netdata/netdata/issues/11388#issuecomment-892055584) |

##### OS / Environment

Not relevant

##### Netdata version

`netdata v1.31.0-150-ge2303fea7`

##### Installation method

Not relevant

##### Component Name

`collectors/`

##### Steps To Reproduce

1. Netdata Agent with running plugins from the list above.
2. Check `/api/v1/info` response.

##### Expected behavior

- [x] freebsd.plugin (fixed in #11398)
- [x] macos.plugin (fixed in #11398)
- [x] charts.d.plugin (fixed in #11390)
- [x] node.d.plugin (insignificant, i guess people only use snmp module)
- [x] statsd.plugin (fixed in #11400)
- [X] ebpf.d.plugin (fixed in #11387)

❗ some plugins are very rarely used/we plan to deprecate them. We can consider not fix them. On the other hand, if the fix is very easy, let's do it.

**Comment by thiagoftsm** [comment]
@ilyam8 I was running a branch here that I am developing and I observed that the following plugins are also missing `module`:

```
{
			"plugin": "apps.plugin",
			"module": ""
		},
		{
			"plugin": "perf.plugin",
			"module": ""
		},
		{
			"plugin": "tc.plugin",
			"module": ""
		},
		{
			"plugin": "idlejitter.plugin",
			"module": ""
		},
		{
			"plugin": "timex.plugin",
			"module": ""
		},
		{
			"plugin": "nfacct.plugin",
			"module": ""
		},
		{
			"plugin": "diskspace.plugin",
			"module": ""
		},
```

Do you think we need to add them for the to do list?

**Comment by ilyam8** [comment]
There is more than that. Not all plugins have modules.

**Comment by ilyam8** [comment]
About the `statsd.plugin` issue.

- we [use the chart source as module](https://github.com/netdata/netdata/blob/a3ec601cda2fd95837d821008d0485a1437f5c80/collectors/statsd.plugin/statsd.c#L1989-L1999) when creating [synthetic](https://learn.netdata.cloud/docs/agent/collectors/statsd.plugin#synthetic-statsd-charts) charts.
- chart source format is [`<line>@filename`](https://github.com/netdata/netdata/blob/a3ec601cda2fd95837d821008d0485a1437f5c80/collectors/statsd.plugin/statsd.c#L1188-L1189) (filename is an absolute path to the file).

So we get "module" like:
 - "48@/etc/netdata/statsd.d/sweet_hodgkin.conf"
 - "2@/etc/netdata/statsd.d/sweet_hodgkin.conf"

I think we need to do the following:
 - use "synthetic_chart" as a "module" for all user configurations.
 - use just `filename` (w/o `line@`, and, perhaps, not abs path, but just filename) for [stock configurations](https://github.com/netdata/netdata/blob/master/collectors/statsd.plugin/k6.conf).
