### ISSUE TITLE
[Feat]: Gap Filling in a parent node for data coming from replicated child nodes

### ISSUE THREAD

**Issue by odynik** [netdata/netdata#12279]
### Problem

The goal is to be able to fill gaps of replicated children nodes on a parent node following a network failure or a parent restart in a simple and fast solution with low complexity.

#### Stage 1
- [x] T1 - Negotiate a new stream protocol version
- [x] T2 - Tx/Rx thread mechanism implementation
- [x] ST2.1 - Initialization
- [x] ST2.2 - Creation
- [x] ST2.3 - Connection
- [x] ST2.4 - Destruction
- [x] T3 - Replication parser
- [x] ST1 - CMDs
- [x] ST2 - Actions

#### Stage 2
- [x] T3 - GAP Awareness & Replication
- [x] ST3.1 - Define input signals for GAP detection
- [x] ST3.2 - Tx/Rx FSM logic implementation
- [x] ST3.3 - CMDs action FSM logic implementation
- [x] ST3.4 - GAPs Queue Timeline implementation

#### Stage 3
- [x] T4 - Dbengine refresh indexing with the new page containing replicated data
- [x] ST4.1 - RData collection to a temporary page
- [x] ST4.2 - dbengine update index with the RData page
- [x] ST4.3 - other memory modes ?? (Ram/save mode can be an intermediate step to verify the replication mechanism)

### Testing end-user scenarios
Testing will be based on the Python+Docker environment to reproduce the scenarios below,
1. - [x] Start the child, start the parent. Disconnect the network. Reconnect the network.
2. - [x] Start the child, start the parent. Shutdown the child. Start the child.
3. - [x] Start the child, start the parent. Shutdown the parent. Start the parent.
4. - [x] Start the parent. Start the child. Repeat 1-3 with this starting sequence.
5. - [ ] Send SIGKILL to simulate crashes. Improve the loading GAP mechanism to handle crashes. 

### Importance

really want

### Value proposition

1. Exploits the distributed nature of the netdata agents to increase data availability.
2. Increase the robustness of the data collection mechanism.

### Proposed implementation

The proposed implementation uses a separate “Replication thread” mechanism. This means a separate pair of Tx/Rx threads to handle the transmission of the missing data between a parent-child architecture.

The replication mechanism objectives are,
1. Negotiate replication availability.
2. Client connects to parent and requests REPLICATE.
3. Parent allows child to connect if API key or machine GUID is allowed.
4. Parent identifies GAPs for each child host.
5. Parent starts the Tx/Rx replication threads to consume generated GAPs.
6. Replication mechanism should settle down when all the GAPs are consumed.

Note: The term `gap filling` and `replication mechanism` are used interchangeably.

**Comment by odynik** [comment]
@cpipilas can you please add the proper product labels in this issue?

**Comment by stelfrag** [comment]
Done
