### ISSUE TITLE
[Bug]: Windows Installer GUI messages need to align with the Cloud terminology

### ISSUE THREAD

**Issue by Ancairon** [netdata/netdata#18704]
### Bug description

The wording on the GUI tool can be more specific, and has foggy terminology. Related to #18703

cc @netdata/product @M4itee 

### Expected behavior

![image](https://github.com/user-attachments/assets/90582717-91c8-42c0-b26a-e1d5d12216cf)

On this screen:

```[tasklist]
### Tasks
- [ ] `Claim your agent on Netdata Cloud` should be changed to `Connect your Agent on your Netdata Cloud Space`
- [ ] `Enter your Token and Cloud Rooms(s).` should be changed to `Please enter your Space's Claim Token and the Room IDs you want the Agent to be added to. If left empty, it will be added to the "All nodes" Room`
- [ ] `Optionally, you can open a terminal to execute additional commands.` I would remove this
- [ ] `Token` -> `Claim Token`
- [x] `Room(s)` -> `Room ID(s)`
- [x] `Proxy` -> `Proxy Address` or `Proxy URL` ?
- [x] Also we need to add pop-ups that explain the final 3 fields (Proxy, Insecure conn, Open terminal) to not need to open Learn to get info on them.
```

**Comment by shyamvalsan** [comment]
Proxy field should be pre filled to app Netdata cloud

**Comment by M4itee** [comment]
It should be a _cloud url_ not a proxy

**Comment by thiagoftsm** [comment]
> It should be a _cloud url_ not a proxy

Hello,

As soon PR https://github.com/netdata/netdata/pull/18649 is merged, we are going to have two options: Cloud URL and Proxy. They are different addresses that can be provided by users.

I will make a different PR to address some of the changes requested here.
