### ISSUE TITLE
improve dimensions visibility

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2746]
This issue tracks all issues related to dimensions' names and units:

- [ ] netdata uses `in` and `out` for disk and swap I/O. They should be `read` and `write`. #2723
- [x] apache bandwidth dimensions use `kilobytes/s`, they should be `kilobits/s` @l2isbad related to #2745 
- [ ] cpu charts should follow the odd/even rule of coloring (odd = good, even = bad), related to #2745 
- [ ] all dimension names (not the IDs that are used by plugins to reference the metrics) should be lower case, related to #2521

**Comment by ktsaou** [comment]
@cakrit 	we should do this with #807 and #4680 	
So, at some point we will have to implement all the breaking changes and increase netdata major version.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
