### ISSUE TITLE
mysql optimization guide using netdata

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#356]
- [x] add the rest of mysql global status variables to netdata #284 
- [x] rewrite the mysql data collector to python (less overheads - thanks to @paulfantom )
- [ ] add documentation to the default dashboard about the mysql metrics #4325 
- [ ] write a blog entry, about monitoring and performance tuning mysql with netdata #4326
- [ ] check if http://mysqltuner.com/ can be integrated somehow

**Comment by ktsaou** [comment]
@PeterZaitsev Peter you have not set an email to your account, so I thought I might reach you via a github issue.

I saw your discussion about high frequency mysql data collection in prometheus and I thought you might be interested in https://github.com/firehol/netdata/ (demo at http://netdata.firehol.org). It can do high frequency data collection from all sources, including mysql.

I will delete this comment. If you are not interested, please ignore it. Thanks (and sorry for the intrusion).

**Comment by titpetric** [comment]
I'd consider rewriting it to Go, I can give a hand if you don't have a short-term ETA? Go compiles statically (32bit or 64bit ELF or whatever), and you'd skip the need for a runtime node env (keep size down). Thoughts?

**Comment by ktsaou** [comment]
> I'd consider rewriting it to Go

This is nice. Go will do too. I use node.js because I can ship its dependencies with netdata, so that the users just need `nodejs` on their systems. But Go, is better in almost all aspects.

**Comment by titpetric** [comment]
There's only the question of the build step. It's possible to build it by docker or golang, but the binaries are usually quite large (10MB range), which is the size of netdata itself. Perhaps I'm overly enthusiastic, but I'd give it a shot at rewriting it at a later release milestone. Feel free to point me in the location of the mysql data collector however, just so I see what I'd be dealing with.

**Comment by glensc** [comment]
yes, go (almost) static linking makes the binaries big, and sometimes can't even strip(1) them as that breaks binaries.

by almost static i mean it still links to shared glibc, but go libraries are static.

**Comment by ktsaou** [comment]
> Feel free to point me in the location of the mysql data collector however, just so I see what I'd be dealing with.

https://github.com/firehol/netdata/blob/master/charts.d/mysql.chart.sh

It is long just because there are many variables / charts. It is simple though:

1. execute: `SHOW GLOBAL STATUS`
2. get the results and print them

The bash version supports multiple servers though. Each server should have its own settings (server to connect to, username, password and possibly other settings to let it connect).

**Comment by ktsaou** [comment]
The plugin should connect to each mysql once and loop through. But an important metric is the connection latency of the server (not currently measured). I would suggest this to happen in parallel, so that if there are connection delays by the server, the core data collection will still work on time.

**Comment by davidak** [comment]
do you know http://mysqltuner.com/ ?

it tells you exactly what settings needs to be tuned.
you could implement something similar to mark on the graphs.

**Comment by ktsaou** [comment]
@davidak nice finding!

**Comment by ilyam8** [comment]
That issue was created when we had only bash mysql collector, it's been a while! Not relevant anymore.
