### ISSUE TITLE
Lint all shell scripts

### ISSUE THREAD

**Issue by paulfantom** [netdata/netdata#4166]
Lint following bash scripts:
- [ ] `charts.d/*` (partly in #4159, #4183, #4261)
- [x] `contrib/*` (#4160)
- [ ] `plugins.d/*` (#4261)
- [x] `docker/*` (#4162)
- [x] `tests/*` + `cppcheck.sh` + `coverity-scan.sh` (#4161, #4262)

Files which were deleted or should be deprecated in following months (shellcheck disabled):
- [X] ~~`installer/functions.sh` (#4161)~~
- [X] ~~`makeself/*` (#4165)~~
- [x] ~~`python.d/python-modules-installer.sh.in` (#4162)~~
- [X] ~~`kickstart*` (#4163)~~
- [X] ~~`netdata-installer.sh` (#4164)~~
