### ISSUE TITLE
Kubernetes monitoring

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#5392]
Kubernetes monitoring is a very complex task.

#5387 is only about monitoring pods/containers, not a kubernetes cluster as a whole.

The task is:
 * investigate what is _kubernetes monitoring_ , analyze other monitoring solutions (a lot of very nice out there).
 * split that big task into smaller pieces.
*  understand in what direction we need to move. 

The big challenge is not to collect data, but represent it in a meaningful way, **which may be not achievable with current netdata implementation**.

I will update OP post with all my finding and thoughts.

**Comment by ilyam8** [comment]
Ports:
 - 2379 (etcd)
 - 8443 (api server)
 - 10248 (kubelet)
 - 10249 (proxy status)
 - 10250 (kubelet)
 - 10251 (insecure scheduler)
 - 10252 (insecure kube controller manager)
 - 10253 (insecure cloud controller manager)
 - 10255 (kubelet read only)
 - 10256 (proxy healthz)
 - 10257 (kube controller manager)
 - 10258 (cloud controller manager)
 - 10259 (kube scheduler)
___
Kubernetes components to monitor.

Location: control plane node, separate nodes?

  - **etcd**
    - `http://localhost:2379/metrics`

Location: master node.
  - **api-server**
    - `https://localhost:8443/metrics`
  - **kube-scheduler**
    - `http://127.0.0.1:10251/metrics`
  - **kube-controller-manage**r
    - `http://127.0.0.1:10252/metrics`
  - **kube-state-metrics**
    - `http://127.0.0.1:80/metrics` (?)

Location: slave node.
  - **kubelet**
    - `http://127.0.0.1:10255/metrics`
    - `http://127.0.0.1:10255/metrics/cadvisor`
    - `http://127.0.0.1:10255/pods`
    - `http://127.0.0.1:10255/specs`
    - `http://127.0.0.1:10255/healthz`
    - `http://127.0.0.1:10255/stats`
    - `http://127.0.0.1:10255/stats/summary`
    - `http://127.0.0.1:10255/stats/container`
    - `http://127.0.0.1:10255/stats/<pod name>/<container name>`
    - `http://127.0.0.1:10255/stats/<namespace>/<pod name>/<uid>/<container name>`
  - **kube-dns** (optional: kubedns, dnsmasq, sidecar)
    - `http://127.0.0.1:10055/metrics`
  - **kube-dns** (default: coreDNS)
    - `http://127.0.0.1:9153/metrics`
  - **kube-proxy**
    - `http://127.0.0.1:10249/metrics`

**Comment by cakrit** [comment]
Sprint 1
- [ ] @ilyam8 : Collect data from the kubelet (port 10255). go collector. Also collect info for each pod/container, if valuable metrics not available to cgroups are provided by the kubelet.
- [ ] @cakrit : Investigate discrepancies between kubelet pods info and API server pods info 
- [ ] @cakrit : Investigate access of endpoints for kube-dns 
- [ ] @cakrit : Helmchart TODOs 1 (https://github.com/netdata/helmchart/issues/1)

Sprint 2
- [ ] @ilyam8 : Collect proxy and DNS metrics
- [ ] @cakrit : Investigate how we can monitor applications running on other pods (e.g. mysql, nginx logs). Perhaps installing a netdata on the same pod? Can we extend at least the collector that get their info via TCP to automatically discover new pods?
- [ ] @cakrit , @ktsaou, @ilyam8 : Extend netdata to accept labels/tags - Design
- [ ] @cakrit , @ktsaou, @ilyam8, @gmosx: Change console UI to present k8s information more meaningfully on each host (right menu) - Design

Sprint 3
- [ ] TBD: Extend netdata to accept labels/tags - Implementation
- [ ] @gmosx: Change console UI to present k8s information more meaningfully on each host (right menu) - Implementation
- [ ] @ilyam8 : Extend existing plugins to autodetect ephemeral pods in a k8s environment e.g. for nginx, apache. Design. (to be discussed)

Sprint 4
- [ ] @cakrit , @ktsaou, @ilyam8, @gmosx: k8s network and service view (cloud) v1 - Design 
- [ ] @gmosx: k8s network and service view (cloud) v1 - Implementation

TBD
- [ ] Investigate access of endpoints for master node endpoints and etcd
- [ ] k8s network and service view implementation (cloud) v2
- [ ] Consider making external plugins trully external (i.e. communication over TCP instead of pipes). Will also help netdata stop running as root. It's related to k8s, because we could just install a collector on the same pod as e.g. apache to read its logs and push them to a netdata daemon (like the prometheus exporters).

**Comment by cakrit** [comment]
Regarding
>  Investigate how we can monitor applications running on other pods (e.g. mysql, nginx logs). Perhaps installing a netdata on the same pod? Can we extend at least the collector that get their info via TCP to automatically discover new pods?

We have two things we need to do, neither of which is related to the helm chart:
 - For collectors that get metrics via TCP, attempt autodiscovery of the the ip/port and perhaps allow specification of endpoints using label-based configuration, or something better if we can manage it. 
 - For collectors that get metrics by reading files, we need to see how people would install netdata as a sidecar container in the same pod. 

The second one is obviously a quick workaround that could be used even for collectors that read metrics via TCP. The caveat is that people would end up installing more netdata instances than what they really need, so we should avoid this with a powerful autodiscovery mechanism.

**Comment by cakrit** [comment]
The plan needs an update, assigning it to the next sprint.

**Comment by cakrit** [comment]
Sprint 1
- [x] @ilyam8 : Collect data from the kubelet (port 10255). go collector. Also collect info for each pod/container, if valuable metrics not available to cgroups are provided by the kubelet. #5639 
- [x] @cakrit : Investigate discrepancies between kubelet pods info and API server pods info #5636
- [x] @cakrit : Investigate access of endpoints for kube-dns #5636 
- [x] @cakrit : Helmchart TODOs 1 (https://github.com/netdata/helmchart/issues/1) #5637.

Sprint 2
- [x] @ilyam8 : Collect proxy and DNS metrics
- [x] @cakrit : Investigate how we can monitor applications running on other pods (e.g. mysql, nginx logs). Perhaps installing a netdata on the same pod? Can we extend at least the collector that get their info via TCP to automatically discover new pods?
- [x] Consider making external plugins trully external (i.e. communication over TCP instead of pipes). Will also help netdata stop running as root. It's related to k8s, because we could just install a collector on the same pod as e.g. apache to read its logs and push them to a netdata daemon (like the prometheus exporters). *This was discussed and doesn't look like we'll be doing (at least not any time soon)*

1.16-rc1
- [ ] @cakrit , @ktsaou, @ilyam8 : Extend netdata to accept labels/tags - Design
- [ ] @ilyam8 : Extend existing plugins to autodetect ephemeral pods in a k8s environment e.g. for nginx, apache. Design. (to be discussed) #5729 

TBD:
- [ ] @cakrit , @ktsaou, @ilyam8, @gmosx: Change console UI to present k8s information more meaningfully on each host (right menu) 
- [ ] Investigate access of endpoints for master node endpoints and etcd
- [ ] Extend netdata to accept labels/tags (Q4 '19)
- [ ] @cakrit , @ktsaou, @ilyam8, @gmosx: k8s network and service view (cloud) (Q4 '19 - Q1 '20)

**Comment by cakrit** [comment]
Plan updated above.

**Comment by cakrit** [comment]
closing this one, tracking in #7903
