### ISSUE TITLE
netdata/packaging: Master issue - overall building pipelines cleanup: improvements, bug fixes, etc

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#5716]
##### Feature idea summary
 This issue is to gather up, track and discuss the work that is taking place for the clean up of existing pipeline implementation. There is a series of activities that has taken place already (for example #5708), this task will serve as master issue to keep track of the overall work required so that we end up with a more extendible and usable pipeline

Issue list
- [X] Docker build process: Split build and publish to distinctive units for better management: #5692
- [X] Restructure coverity scanning process: #5656 
- [x] Introduce travis notifications at the stage level #5761 
- [x] Reorganise travis pipeline stages (use distinctive names, split up the work differently, make identification of failed activities easier on Travis UI rather than the logs themselves by adding more steps, etc) #5761

Notes: 
1) There is some work that has taken place as part of other issues and is not mentioned here. We can 
2) The issue will be further refined as we gain more experience and insights on our infrastructure

##### Expected behavior
Revamped travis pipeline implementation that will have clearer workflow, more precise logging and easy debugging by repositioning some activities so that it is easier to narrow down when something breaks
