### ISSUE TITLE
feature: kubelet collector improvements

### ISSUE THREAD

**Issue by ilyam8** [netdata/netdata#5720]
##### Feature idea summary

just copying from #5639 so we can close it

suggested alarms:
 - [x] `get_token_fail_count`
non-zero get_token_fail_count means alarm.
 - [x] `kubelet_docker_operations_errors`
It looks dangerous to add an alarm here, but let's put one on the sum of all the dimensions, looking e.g. for the avg of the last minute, with a delay. The idea is to not make this one too sensitive, but not miss suddently repeated errors.
 - [x] `kubelet_node_config_error`
1 means alarm.
 - [x] `kubelet_runtime_operations_error`
It looks dangerous to add an alarm here, but let's put one on the sum of all the dimensions, looking e.g. for the avg of the last minute, with a delay. The idea is to not make this one too sensitive, but not miss suddently repeated errors
 - [x] `kubelet_pleg_relist_interval_microseconds`, `kubelet_pleg_relist_latency_microseconds`
There are a lot of requests going there, so I think we can safely compare previous to current period for each dimension and alert with greatest sensitivity for 0.5, lower sensitivity for 0.9 and lowest for 0.99.
