### ISSUE TITLE
feature: kubelet collector improvements (leftovers from #5720)

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#5824]
##### Feature idea summary

just copying from #5720 so we can close it

- [x] lower the priority of kubelet and kube-proxy charts so we see them before cgroups
- [ ] (LATER)`kubelet_docker_operations_latency_microseconds` (sum per operation type), `kubelet_runtime_operations_latency_microseconds` (sum per operation type), `storage_operation_duration_seconds_bucket` (sum per volume plugin per operation)<br>
We will not add them right now and discuss what would be the appropriate place to put a filter that would prevent potentially unwanted charts from taking up memory and disk space (i.e. filtering on the chart level).

 - [x] kubelet_container_log_filesystem_used_bytes

___

suggested alarms:
 - [ ] `apiserver_audit_requests_rejected_total`
An alarm that compares a previous period average (say 5-10min) vs current period average (say 1min).
 - [ ] `apiserver_storage_data_key_generation_failures_total`
An alarm should again compare previous period with current.
 - [ ] `apiserver_storage_envelope_transformation_cache_misses_total`
A conservative alarm that again looks at a previous period vs a current period and is triggered on a significant difference.
 - [ ] `apiserver_storage_data_key_generation_latencies_microseconds_bucket`
No alarms defined for dimensions up to 80ms, then increasingly sensitive alarms for 160, 320, 640 and always alarm on the ones from 1280 and above. Of course we'll need one alarm for each dimension (bucket) and we'll be able to refine it based on user feedback.
 - [ ] `rest_client_requests_total`
Alert on code=`<error>`.

**Comment by ilyam8** [comment]
i added most important features, moved other to #6000
