### ISSUE TITLE
[Master issue][netdata/packaging]: Integrate netdata to Digital Ocean - Spike

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6009]
##### Feature idea summary
We are in the process of integrating our software within Digital Ocean, to enable easier access to netdata valuable offering for Digital Ocean users. 

In short the activities that will be taking place include:
- [x] Provide clear instruction set for Digital Ocean users, on how to install and configure netdata within a DO droplet
- [x] Implement netdata as a 1-Click Application within Digital Ocean
- [x] Implement tools that will help simplify and automate master-slave configurations

CC: @ktsaou @cakrit 
##### Expected behavior
Netdata to become a valuable asset within Digital Ocean domain that will help users get the best experience on host monitoring and alerting

**Comment by cakrit** [comment]
This was done a while back.
