### ISSUE TITLE
Scope of 1.16-rc2

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#6243]
### After this sprint our users will be able to
- [ ] Disable alerts in a simpler way - @thiagoftsm 
- [ ] Monitor VMWare machines and ESXI hosts - @ilyam8 
- [x] Monitor dnsmasq dhcp leases - @ilyam8 
- [x] Collect [pi-hole](https://pi-hole.net/) statistics - @ilyam8 
- [x] See more detailed CPU performance metrics - @vlvkobal 
- [ ] use TLS encryption on backends - @thiagoftsm 
- [ ] Document detailed support information per distribution (Code health, CI coverage, installer state, packaging availability, etc) - @paulkatsoulakis 
- [ ] Receive release versions of netdata, for the LTS versions of most major distributions (Debian,Ubuntu, Centos, Fedora, Redhat, openSuSE, Gentoo), through netdata's newly introduced repository infrastructure - @paulkatsoulakis
- [ ] Change the granularity of data collection without losing the older metrics that have already been gathered and stored @mfundul

### We are also working on delivering the following
- Repeating notifications for alarms  **(100%)**  - @thiagoftsm 
- Caching for static resource **(100%)**  - @thiagoftsm 
- Improve netdata installers (kickstarts, static binaries, base install process) **(100%)**  - @paulkatsoulakis 
- Enrich our CI infrastructure with cross distribution testing, starting with basic install and run for all distros **(100%)**  -  @paulkatsoulakis
