### ISSUE TITLE
Scope of 1.17-rc2

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#6492]
### After this sprint our users will be able to
- [ ] Disable alerts in a simpler way - @thiagoftsm 
- [ ] Monitor VMWare machines and ESXI hosts - @ilyam8 
- [ ] Collect mongodb sharding metrics - @ilyam8 
- [ ] Mongodb ssl connection support - @ilyam8
- [ ] use TLS encryption on backends - @thiagoftsm 
- [ ] Document detailed support information per distribution (Code health, CI coverage, installer state, packaging availability, etc) - @paulkatsoulakis 
- [ ] Deliver an updater mechanism for kickstart-static64.sh install script - @paulkatsoulakis
- [ ] Change the granularity of data collection without losing the older metrics that have already been gathered and stored @mfundul

### We are also working on delivering the following
- MongoDB backend (70%)  - @vlvkobal
- Prepare for the delivery of netdata as an 1-Click environment on Digital Ocean marketplace (dicitalocean.com) **(100%)** - @paulkatsoulakis 
- Focus on long standing bugs around packaging and installers **(70%)** - @paulkatsoulakis 
- Configuration management -- In collaboration with the team **(40%)** - @paulkatsoulakis
