### ISSUE TITLE
Enhance the testability of the Netdata internal web-server.

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#6496]
##### Summary

There have been problems with the current URL parsing code, there are currently some URLs that return the wrong status code (e.g. 200 instead of 404). In order to clean up the web API we will replace the current URL parsing with [picoparser from h2o](https://github.com/h2o/picohttpparser). The goal of this task is make the API URL-handling code testable.

- [x] Fuzz-test the API (generate from swagger).
- [x] Customize the fuzzer to check database interactions, response formats (matching swagger defs) and return codes of requests.

---

- [ ] Bring the parsing code into the project
- [ ] Replace the URL parsing: flatten some of the call-chains in the API responses, pull parsing code into a common point.
- [ ] Build unit tests to check the picoparser code.
- [ ] Build unit tests to check the glue between picoparser and our header parsing.

---

- [ ] Build performance tests (wrk) to check behaviour under load.
- [ ] See if we can put the set of fuzzing urls into wrk as a payload generator.

##### OS / Environment
All

##### Component Name
Web server

**Comment by thiagoftsm** [comment]
Hi @amoss ,

As suggestion for the first step, I would begin changing the function `http_request_validate()` that is inside the file `web/server/web_client.c`, I would say that around 75% of the function can overwritten with the function `phr_parse_request()` from libh2o, probably we do not need to link now Netdata with libh2o for this specific function, because we can easily move the files `picohttpparser.c' and `picohttpparser.h` from h2o webserver direct to our directory `libnetdata/url/`.

An important thing that we need to keep in our mind it is thefact that `phr_*` functions are used to parse HTTP request, I would suggest you do not expect more than 64 headers in a request, I confess I do not see necessity to have more than this for our necessities, but I can be wrong.

It is expected that after we overwrite the body of the function `phr_parse_request()` Netdata must have a good improvement when we use `wrk` to measure the results, I am saying this, because according H2O this is one of the greatest features they have.

Best regards!

**Comment by Ferroin** [comment]
> An important thing that we need to keep in our mind it is thefact that phr_* functions are used to parse HTTP request, I would suggest you do not expect more than 64 headers in a request, I confess I do not see necessity to have more than this for our necessities, but I can be wrong.

I would tend to agree, but we should make absolutely certain that we fail gracefully if we get too many headers.  Cases like this are a common location for security issues.  Unless I'm mistaken, the correct status code if we get too many headers should be 431 as outlined in [RFC 6585](https://tools.ietf.org/html/rfc6585).

**Comment by amoss** [comment]
Removed the sprint milestone - it should not be tagged on Epics, only their contained issues.

**Comment by ilyam8** [comment]
Closing this feature request. We will re-evaluate the request internally.
