### ISSUE TITLE
migrate dashboard.js to React

### ISSUE THREAD

**Issue by jacekkolasa** [netdata/netdata#6515]
We are starting to migrate dashboard.js to React/Redux/Typescript stack. We want to achieve full backwards compatibility for all standard use-cases, and also maintain support for undocumented global settings, which are stored in `window.NETDATA` global object.

This is a sketch description of steps needed, but the list can be (slightly) changed during the work.

Here's how the final result should look like:

- dashboard.js file should include everything that is needed for it to work, as it was before. It needs to do the following:
  - Do all the work which is needed for backwards-compatibility reasons, that is mainly creating a global `NETDATA` object
  - create react root DOM node
  - load the react app. Normally the bundled react .js file should be placed at the end of the `body`, but `dashboard.js` needs to be placed before the `body` (to allow global `window.NETDATA` overrides) so we need to make sure the react app is ran at the right moment.
- updating to new `dashboard` should be instant. In case of bugs, we'll leave old dashboard.js in the repository under different name (`dashboard-old.js`). There will be a flag which could be toggled if for some reasons (i.e. regression bugs) user wants to use the old dashboard.
- we plan to use create-react-app (CRA) as a starting point. If it will be not enough, then we'll be working directly with `webpack`
- dashboard.js will be compiled at the build time by node.js, which should be available during agent compilation time
- available (exposed) configuration options should be listed and groomed by the team - leaving too many options is harder to maintain, so we need to find a sweet spot
- development task should be created, which should take any .html file into the dev environment and run CRA in development mode, with hot-reload
- any global state should be transformed into local/redux state, for better visibility
- any global configs should put into separate utility, so it's easy to see all the dependencies and possible configuration combinations
- react DOM node will actually not be used - but React app will use our "directives" (`<div data-netdata="unique.id"></div>`) and render the DOM inside as React Portals. This way users can still build static `html` which our `dashboard` will later enhance using multiple portals with react/redux ecosystem

To do a smooth refractor, I'm trying to do it step by step - having the app working with legacy `dashboard.js` and replacing small parts one after another. To do this, i plan to replace old-school callbacks by dispatching redux actions. Also, to make the refractor easier it's possible that some parts/components will not be structured as a fresh well-thought app. I think it's better to transform everything to React Components making sure it works, and later eventually do a subsequent refractor, because refractoring React App is much easier than refractoring legacy code to React.

# Tech choices

- Redux - for state management
- Redux-saga - we decided to use this to manage side-effects and asynchronous flow in Redux
- Reselect
- Typescript
- rest properties and ramda.js for updating state in reducers

# Progress
- [x] add create-react-app with development task
- [x] configure linter
- [x] assign necessary window. assignements before the app starts (backwards compatibility)
- [x] Generate portals in place of `[data-netdata]` elements
- [x] redux store configuration
- [x] pass chart-details chart-data to react app (redux dispatch in legacy code)
- [x] transform DOM attributes of `[data-netdata]` elements
- [x] migrate units-conversion
- [x] create chart container with legend, toolbox
- [x] Dygraph: pass attributes needed for painting
- [x] Dygraph: configure axes
- [x] migrate formatters
- [x] migrate globalSelectionSync state, connect to Dygraph
- [x] hook legend state to redux (dimensionsVisibility)
- [x] hook toolbox to redux
- [x] migrate globalPanAndZoom
- [x] migrate globalChartUnderlay state
- [x] migrate pause logic 
- [x] migrate tooltips
- [x] migrate common- min/max helper
- [x] configure Sparkline charts
- [x] configure Peity charts
- [x] configure Google charts
- [x] configure D3pie charts
- [x] configure D3 charts
- [x] configure Easypiechart
- [x] configure Gauge charts
- [ ] configure global reset (needed by main.js)
- [x] setup intersectionObserver (toggling visibility)
- [ ] support snapshots
- [x] migrate alarms
- [x] use registry in react app
- [ ] localstorage logic

**Comment by Daniel15** [comment]
I'm a bit late to reply here, but why Redux rather than just using something simpler like React's useReducer hook?

**Comment by jacekkolasa** [comment]
i don't think it's too late, it still is quite easy to change where we're storing the state. Few reasons i think of now:
- charts have some common state, like chartUnderlay, selection, panAndZoom, commonColours. i think Redux will only be used when charts will be in sync. When possible, local state will be used
- we need to focus heavily on performance and `reselect` can help with that. Also instead of "props drilling", we can use `useSelector` down the tree
- Redux was handy during refractor, because old dashboard code could dispatch actions to new dashboard

How does that sound to you?

**Comment by ndom91** [comment]
Hey just wondering what the status of this issue is? Has this been shipped? It doesnt seem to be mentioned anywhere else in the docs.

**Comment by underhood** [comment]
@jacekkolasa should we close this?

**Comment by jacekkolasa** [comment]
@underhood YES! :) Thanks!
