### ISSUE TITLE
Scope of 1.17

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#6600]
### After this sprint our users will be able to
- [ ] `mongodb`: collect sharding metrics - @ilyam8 
- [x] `myqsl`: collect per replication channel metrics - @ilyam8 
- [ ] `python.d`: auto-detect retry previously running jobs after a system restart  - @ilyam8 
- [ ] Change the granularity of data collection without losing the older metrics that have already been gathered and stored @mfundul
- [ ] Archive metrics to a MongoDB database in a nonblocking way - @vlvkobal
- [ ] Monitor process uptime - @vlvkobal
- [ ] `alarms`: Template for alarm dimensions - @thiagoftsm 
- [ ] `alarms`: Alarms activaded only when more than one alarm is raised. - @thiagoftsm 
- [ ] `alarms`: Max alarm on any dimension. - @thiagoftsm

**Comment by gpapamathND** [comment]
@ilyam8 , @vlvkobal @paulkatsoulakis @jacekkolasa @mfundul @thiagoftsm 
Please add the scope of 1.17
