### ISSUE TITLE
Scope of 1.17-Sprint4

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#6685]
### Team Capacity
Story Points: `51 `
Size of Team: `6 team members`

### Major Goal 
- [x] Release version 1.17 - Core Team

### After this sprint our users will be able to
- [ ] `go.d`: auto-detect retry previously running jobs after a system restart   - @ilyam8 
- [ ] `python.d`: auto-detect retry previously running jobs after a system restart  - @ilyam8
- [ ] `vCenter` Server Appliance health status monitoring - @ilyam8 
- [x] Change the granularity of data collection without losing the older metrics that have already been gathered and stored - @mfundul
~- [ ] Archive metrics to a MongoDB database in a nonblocking way - @vlvkobal~
- [x] Monitor process uptime - @vlvkobal
- [ ] `alarms`: Alarm templates for all dimensions of a chart - @thiagoftsm 
- [ ] `alarms`: Links to alarms in notifications should always center the chart on the timeframe  - @thiagoftsm 
- [x] `HTTP`: HTTP errors inside web api more readable - @thiagoftsm 
- [ ] `ubuntu`: make cups package optional - @paulkatsoulakis 
- [x] `ubuntu`: wrong default paths in /etc/netdata/edit-config - @paulkatsoulakis 
- [ ] `[Binary releases]` Establish Gentoo portage repository and infrastructure - @paulkatsoulakis 

### We are also working on delivering the following
- [ ] `[research]` collect metrics using docker remote api  - @ilyam8 
- [ ] `[research]` Metrics Map Research - @mfundul
- [x] `[refactoring]` migrate dashboard.js to React - @jacekkolasa
