### ISSUE TITLE
Scope of 1.18 Sprint 2

### ISSUE THREAD

**Issue by gpapamathND** [netdata/netdata#6857]
### After this sprint our users will be able to
- [ ] [HDFS](https://hadoop.apache.org/docs/r1.2.1/hdfs_design.html) monitoring @ilyam8 (#4890)
- [ ]    - Prepare the migration for new libraries that will allows to use Microsoft and communicate properly with cloud  #6831@thiagoftsm
- [ ] `[QA]` Make dbengine the default memory mode. - @mfundul

### We are also working on delivering the following
- [ ] [refactoring] make archiving engine modular, testable, and maintainable - @vlvkobal
