### ISSUE TITLE
Remove backends subsystem

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#7017]
##### Feature idea summary
The last step of releasing a new exporting engine. After a transition period has ended:
- [x] Announce the removal.
- [x] Remove backends folder and `health.d/backend.conf`
- [x] As far as we agreed to use new names for connectors as stated in #6769 (Terminology section of the design document), all related directories, files, functions, and variables should be renamed.
