### ISSUE TITLE
Does not inform sufficiently of intent to report my data to Google Analytics

### ISSUE THREAD

**Issue by sneak** [netdata/netdata#7366]
The netdata installer says the following:

```
  The following changes will be made to your system:

  # USERS / GROUPS
  User 'netdata' and group 'netdata' will be added, if not present.

  # LOGROTATE
  This file will be installed if logrotate is present.

   - /etc/logrotate.d/netdata

  # SYSTEM INIT
  This file will be installed if this system runs with systemd:

   - /lib/systemd/system/netdata.service

   or, for older Centos, Debian/Ubuntu or OpenRC Gentoo:

   - /etc/init.d/netdata         will be created


  This package can also update a netdata installation that has been
  created with another version of it.

  Your netdata configuration will be retained.
  After installation, netdata will be (re-)started.

  netdata re-distributes a lot of open source software components.
  Check its full license at:
  https://github.com/netdata/netdata/blob/master/LICENSE.md
Please type y to accept, n otherwise:
```

However, it does not tell me that it's going to silently spy on me.  I don't consent to analytics.  It spied on me and sent my data away without my consent.  I had to uninstall it, clean my system, and reinstall it using an obscure, barely-documented flag.

This is not respecting user consent.  Notify the user before spying on them, if you intend to do so, so they have an opportunity to cancel and delete your software if they don't wish for that to happen.

**Comment by jogster** [comment]
As someone that is just setting this up - what default analytics were published and how?

**Comment by cakrit** [comment]
Hi @sneak,

The info regarding telemetry has been prominently featured in the [Anonymous Statistics](https://docs.netdata.cloud/docs/anonymous-statistics/) section of our documentation, it is part of our [Privacy policy](https://docs.netdata.cloud/docs/privacy-policy/), it's mentioned in the [Security documentation](https://docs.netdata.cloud/docs/netdata-security/#opt-out-of-anonymous-statistics) and displayed in a [`netdata-installer.sh` message](https://github.com/netdata/netdata/blob/master/netdata-installer.sh#L866)

These places have the information, because users requested it to be there, in order to make it prominent. We have never denied a request to improve visibility into telemetry and you're welcome to do a PR to improve the text of the particular installer (files are under `packaging/makeself`).

We don't appreciate the term "spying", as we have done our best to prevent to ensure that no  information that could identify any users or specific systems is transmitted and continue to accept recommendations on how to make this clearer. We do not intend however to change telemetry to opt-in, as we need at least some basic aggregated metrics, to help us make decisions (e.g. on the OS versions that we need to prioritize in our binary packaging distros and test automation).

**Comment by sneak** [comment]
> we have done our best to prevent to ensure that no information that could identify any users or specific systems is transmitted and continue to accept recommendations on how to make this clearer. 

False; The user's IP address, which is personally identifying information (PII) is transmitted with the analytics.  Google receives the user's usage data, *plus* their IP address, which is identifying.

The fact that the data that you collect by spying is useful to you does not make it not spying.  The fact that Google doesn't provide *you* with the IP address information doesn't mean that personally identifying information isn't being transmitted.  Those are facts.

> We do not intend however to change telemetry to opt-in, as we need at least some basic aggregated metrics, to help us make decisions 

You don't *need* that information, you *want* that information.  It's reasonable to want that information.  What's not reasonable is to pretend that you're not violating user consent.

Fact: **I was given no opportunity to opt out, no notice that my identifying information would be transmitted before your software did so.**

**Comment by ktsaou** [comment]
@sneak you are right that we need to make it clear that anonymous statistics are by default enabled. @cakrit please make sure we add the relative information everywhere. Also, the kickstart script requires an ENTER to be pressed, so please make sure anonymous statistics logs a line at that point, before actually installing anything.

@sneak however, you have a misunderstanding on PII. It is actually a common misunderstanding among most engineers (even security engineers), and I think it comes from the fact that GDPR considers IPs as PII.

IP addresses, phone numbers, etc are PII only when they can be potentially correlated with your identity, that is only when someone can somehow relate this IP, phone number, etc to your name. If this correlation cannot happen, the IPs are just IPs, not PII.

In our case, this correlation cannot be done. We do not have any means to correlate the IP address with any person.

Of course, you may think that we can't, but probably Google can. For this case, complying with GDPR, GA has an option to anonymize IPs. We have enabled this option, so even Google cannot correlate IPs with your identity.

Our intention is never to spy our users and we will comply with anything required in that respect.

**Comment by cakrit** [comment]
So our TODOs here are:
1. Indicate in all installers before the Enter/yesno: "Anonymous statistics will be [enabled/disabled]", according to the provided option. 
- [ ] netdata-installer.sh / kickstart.sh 
- [ ] kickstart-static64.sh
- [ ] binary packages (not sure about this one)

2. Better document the different ways of running the installer:
- [ ] In our website, we'll add options stable/nightly, auto-updates:on/off, anonymous statistics (on/off) and accordingly generate the correct kickstart.sh command (the texts won't be exactly like this, to be discussed)
- [ ] In docs, we'll make the options more prominent, at least for the same three options (telemetry, auto-updates, stable/nightly).

**Comment by jogster** [comment]
Btw guys - my intention was never to impugn anybody, least of all netdata. I only came across this product a few days ago and was able to start using it with relative ease.  I was just curious how it worked. I'm just in the process of understanding the statd plugins and figuring out how to create custom charts. So far the experience has been incredibly positive!

**Comment by sneak** [comment]
Why not just ask the user if they want to participate? You’re already prompting them for a confirmation during install. Have the default for slapping enter be yes, but allow them to type n/no if they wish.

**Comment by sneak** [comment]
> Of course, you may think that we can't, but probably Google can. For this case, complying with GDPR, GA has an option to anonymize IPs. We have enabled this option, so even Google cannot correlate IPs with your identity.

Yes, for users in places where GDPR applies. Let’s also not forget about the practices of the intelligence services (thank you, Ed Snowden!) in the country in which Google operates. They don’t give two fucks about four fucks about what the GDPR says is or isn’t legal.

**Comment by sneak** [comment]
We can squabble all day about what is or isn’t PII: you didn’t have my consent when your software made my computer connect to Google. It wasn’t what I wanted when I installed a locally-hosted monitoring package. It wasn’t disclosed. 

You can get just barely on the right side of ethical by disclosing it clearly first, but why not just *ask* for consent?

**Comment by ktsaou** [comment]
> Are you afraid that too many people would say no? If that’s the case, using your analytics data _today_ is unethical, based on the assumption that most users would say “please do not spy on me” when asked directly.

No, this is not the case. We don't want any questions or any configuration during install. This is the whole point with netdata. One command, no questions, done!

We are always trying to give sane defaults. There are hundreds of thousands of options available, but for everything we ship sane defaults.

So, we want anonymous statistics enabled by default, we don't want to ask questions, but we should let people know this is the default and how to change it, even before installation.

**Comment by sneak** [comment]
> We don't want any questions or any configuration during install. 

You are already asking a question today during install, as shown above.

**Comment by ktsaou** [comment]
The only question there is today is like this:

```
We will do the following:

- this
- that
- the other

If you agree, press ENTER > 
```

So, in the list we will also include the anonymous statistics status.
I think this will be enough.

If we start adding individual questions, then a lot of people will start requesting all kinds of things to be decided before installation, like "do you want to enable a registry? do you want to enable netdata.cloud? do you want collect security metrics? do you want to enable statsd? do you want the api to be enabled by default?" and many, many, many more.

The only sane answer to all those questions, is that we ship sane defaults, and we never ask questions. A good overview is all that is required and proper instructions so that everyone will know what will get.

**Comment by sneak** [comment]
You’re in charge; you get to say “yes, we should ask for consent for uploading telemetry because privacy belongs to the user, however we will say no to asking other configuration questions because we want to keep the experience streamlined.”

If you make the opt-out option clear in the message right there under the notification, all you’re going to do is make most users (who don’t want to be spied on) press a more keys: ^C, up arrow, space, disable telemetry flag, enter.

It’s not simpler; it’s actually a lot more complex. And in the minority case (those who don’t mind the privacy loss), you’re only saving them one keystroke.

**Comment by sneak** [comment]
PS: that URL at the bottom of the current confirmation screen seems to 404

**Comment by sneak** [comment]
> *So, in the list we will also include the anonymous statistics status.*

Please stop calling them that. **It is not, and will never be anonymous.** Calling it anonymous is a **false statement**.

**Comment by ktsaou** [comment]
@sneak thank you for this information.

Could you please point to the relevant laws that justify what you describe?

**Comment by sneak** [comment]
Spyware is legal. There are no laws in most countries that require that you behave ethically when releasing software that spies on its user.

**Comment by titpetric** [comment]
@ktsaou would it be possible to move the telemetry opt out flag into the final server binary, as an argument or config, instead of opting out at build time? It would also avoid issues like having to build docker images without telemetry specifically, but just letting the user know which flag to use to opt out (if that stays the default behaviour).

Obviously I don't want to disable it for titpetric/netdata, as I feel that the project actively disclosed everything that was needed vis a vis GDPR and transparency practices. Regardless if the IP is recorded or not recorded on Google Analytics side, there isn't a technical measure to have telemetry, and at the same time not transmit that data over IP. The main issue is that it's just difficult to opt out, requiring a custom build/install.

**Comment by cakrit** [comment]
> @ktsaou would it be possible to move the telemetry opt out flag into the final server binary, as an argument or config, instead of opting out at build time? It would also avoid issues like having to build docker images without telemetry specifically, but just letting the user know which flag to use to opt out (if that stays the default behaviour).
> 
> Obviously I don't want to disable it for titpetric/netdata, as I feel that the project actively disclosed everything that was needed vis a vis GDPR and transparency practices. Regardless if the IP is recorded or not recorded on Google Analytics side, there isn't a technical measure to have telemetry, and at the same time not transmit that data over IP. The main issue is that it's just difficult to opt out, requiring a custom build/install.

Reply below is also a question/request to @knatsakis and @ncmans

What options do we have in the docker run command/docker-compose file  that we could utilize? I think that a user could just provide an option to mount any file whatsoever to `/etc/netdata/.opt-out-from-anonymous-statistics` (we only check for the existence of such a file). 
Whatever the method will be, we need to 
- [ ] Document how to opt-out when using docker images

Slightly relevant:
- [ ] We should add an option to opt-out, to  `netdata/helmchart`

**Comment by sneak** [comment]
The worst part of GDPR is that it confuses people about the difference between “not illegal” and “unethical”.

IPs uniquely identify users. This means that IPs are personally identifying information. They identify persons, and are thus personally identifying information. The GDPR’s opinion on whether or not they are “PII for purposes of GDPR regulation” is not relevant to these objective truths. Please do not confuse them.

Silently transmitting telemetry data without the consent of the user is deeply unethical. It uses their computer hardware and their network connection to spy on them, against their wishes. It is not something ethical developers do, regardless of the GDPR or any other local legislation. 

Transmitting data about the user without their knowledge makes the software package spyware.

Please don’t ship spyware.

**Comment by sneak** [comment]
If you insist on being unethical and silently opting your users (most of whom will not consent to your spying, if asked), then consider using this standard environment variable:

https://consoledonottrack.com

**Comment by sneak** [comment]
Be advised, however, that I am currently compiling for publication and publicity a list of commonly used (but not widely known as spyware) applications such as Netdata, and continuing to automatically assume that users are fine with your spying (you will find that most are not, if you ask them) will result in Netdata being featured prominently in the list of spyware applications.

Louder notification will help, sure, but will not resolve the core problem of developers feeling entitled to user metrics without their users’ consent.

**Comment by ilyam8** [comment]
> IPs uniquely identify users.

Probably i m missing something but this is not true. Was working in a big ISP and IP address says nothing. There are either big public ip pools or CGNat. The only thing you can identify is a country, not even a region. To identify user you need netflow data + data from billing system. This is confidential info and can be requested only by the police or something.

**Comment by titpetric** [comment]
Support for ENV would be great for docker, support for command line flags
would be great for systemd/etc and generally for cli mode, and ultimately
yeah a file/config opt out as well.

The file/config option I believe is the hardest for a user, as it’s
mandatory for them to find this info in the online docs, while env can be
documented in the dockerfile, and the command line flag can be documented
in the cli under - -help opt as is commonly used.

I think the opt out should be accessible for headless installs like docker.
Defined default ARG/ENV is the Dockerfile way, command line arguments a bit
less as they are documented in the binary, not the Dockerfile.

**Comment by TheOldMan2000** [comment]
Just my two cents, I'm no lawyer, I use GA minimally on my own websites, but the whole point of GDPR is that people are considered opted OUT by default, they must choose to opt in and there has to be a record of them doing so. The clock reset on GDPR launch day. 

There also can be nothing vague or unclear in the provision of the question (a tiny checkbox, small print, hard to disguise colours etc). From newsletters, to analytics, it doesn't matter what the format is. If you provide services to anyone in the EU, whether free or otherwise, you have to respect that underlying principle of GDPR. Yes, GDPR is a PITA but it's a necessary evil and inconvenience these days. It's after all about giving people back control over their data and information and to be honest, if you have tens of thousands of users that you are collecting data from, you definitely need to make sure everything is 100% correct.

There is nothing wrong with reviewing the decision or ensuring your understanding, in fact it's a requirement to regularly review your GDPR policy, say once a year to ensure it's relevant, up to date, you still have a recognised reason for collecting the data etc.

So if I might make a suggestion, immediately disable GA. Review your GDPR compliance. Then if you don't want to have the installer stopping to ask if users if they want to opt in to Google Analytics, then either have two clearly marked installers (one without GA enabled and one with), or disable GA by default and let users OPT IN via changing a setting in netdata.conf.

**Comment by titpetric** [comment]
> Article 6
>
> Lawfulness of processing
> 
> 1.   Processing shall be lawful only if and to the extent that at least one of the following applies:
>
> ...
> (b) | collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or *statistical purposes* shall, in accordance with Article 89(1), *not be considered to be incompatible with the initial purposes* (‘purpose limitation’);

And:

> Article 89
> 
> Safeguards and derogations relating to processing for archiving purposes in the public interest, ?scientific or historical research purposes or statistical purposes
>
> 1.   Processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes, shall be subject to appropriate safeguards, in accordance with this Regulation, for the rights and freedoms of the data subject. Those safeguards shall ensure that technical and organisational measures are in place in particular in order to ensure respect for the principle of data minimisation. Those measures may include pseudonymisation provided that those purposes can be fulfilled in that manner. Where those purposes can be fulfilled by further processing which does not permit or no longer permits the identification of data subjects, those purposes shall be fulfilled in that manner.

As was already written above:

> In our case, this correlation cannot be done. We do not have any means to correlate the IP address with any person.
> 
> Of course, you may think that we can't, but probably Google can. For this case, complying with GDPR, GA has an option to anonymize IPs. We have enabled this option, so even Google cannot correlate IPs with your identity.

Either way, none of us are lawyers, but GDPR has 6 rules for processing data, of which consent is only one. You can have implicit consent, if the service you're implementing covers one of the remaining five processing rules, and it does.

**Comment by cakrit** [comment]
Let's be very clear here, because the conversation is steering off course. Netdata does not collect any personal information whatsoever. It's wrong to even talk about associating IPs with persons, when we anonymize them. There's little we can do about people don't trust Google's statements regarding [IP Anonymization](https://support.google.com/analytics/answer/2763052?hl=en). 

Let's be clear, it is in our legitimate interest to not request opt-in for the anonymous statistics. It makes all processes smoother and allows us to get at least a statistically significant sample of the systems netdata is running on. It's not a matter of "wanting" the information, we "need" it, in order to make strategic decisions about the future of the FOSS agent. 

Even GDPR (which **does not apply** to the information we collect, by any stretch of the imagination) allows data collection AND processing for [legitimate interest](https://www.gdpreu.org/the-regulation/key-concepts/legitimate-interest/), but that point has already been addressed. So, let's talk about ethics, not because we believe we must, but because we have nothing to fear.

There is literally no way @sneak or anyone else can expect everyone in the world to agree with them on morality. The discussion will inevitably boil down to first principles and moral relativism wasn't born yesterday. Even if we somehow assume that the people in this discussion share generally accepted norms, it's impossible for all of us to agree. I personally see absolutely no harm to anyone from maintaining an opt-out mechanism from anonymous statistics. We continue our efforts to improve on this matter only because transparency is one of our core values. 

We will plan the implementation of the suggested measures (other than opting-in) as soon as possible.

**Comment by sneak** [comment]
Okay, let’s stick to facts. 

I paid money for my computer and my internet connection. 

Netdata used those things to silently transmit my personal data against my wishes, without my consent. Interpret that within your own personal framework of morality however you like.

> Let's be clear, it is in our legitimate interest to not request opt-in for the anonymous statistics. It makes all processes smoother and allows us to get at least a statistically significant sample of the systems netdata is running on. It's not a matter of "wanting" the information, we "need" it, in order to make strategic decisions about the future of the FOSS agent.

Thank you for your honesty, and your oblique implication that most of the users would not consent (and thus not provide) you with this data if you asked first. 

You absolutely do not *need* it, which is why you put it in quotes.

**Comment by sneak** [comment]
Now that you have admitted the direct financial interest in silently violating the human rights of your users, now is the time to hold and internal ethics review meeting and begin taking steps to act in an ethical manner with regards to your users’ hardware and personal data (usage information, which is not yours).

The first step will be to immediately cease distribution of the software that violates human rights, and to reinstate it only after it has been amended to ask for consent to use a user’s personal data and hardware in a way that serves your financial interests.

**Comment by titpetric** [comment]
Hey @sneak - I see that all reason has left you (or wasn't there to begin with), so let's stick to the facts. If you don't want people to see your IP, may I suggest that you cancel your ISP contract and thus prevent your IP being transmitted to potentially morally or literally harmful organisations.

Or perhaps, since your ISP has a financial interest in keeping you as a subscriber, and this is your direct financial cost, maybe you can raise your concerns with them as they are the enabler of sending your IP all over the internet. Maybe this provider is even... *gasp* Comcast, which is already known for their [controversies](https://en.wikipedia.org/wiki/Criticism_of_Comcast). Your moral absolutism can be directed at anyone, why not the first member in the chain? After all, they are the one who are passing on your IP packets, maybe even logging them and sending them to NSA? Who knows. The possibility is there, so by your reasoning they are absolutely violating human rights as well.

Not reading the documentation isn't an excuse for your outbursts. Not all information is created equal, so there is a huge difference between making a request with statistical data, and as you say, "your activities", or at the extreme end of the spectrum, identifying data like emails, addresses, SSNs, CCs, CVVs, and what else is there. If anything, netdata is benefiting from the statistical information to ensure reliability and diagnostical information for their product which in turn would benefit you as the user, and the community as a whole.

You should first realize that open source software since the beginning is [Gratis vs. Libre](https://en.wikipedia.org/wiki/Gratis_versus_libre), where in this case, you have the freedom to choose to use or not use, or *modify (recompile with opt out)* something that's provided at no cost to you. Moral absolutism isn't a justification to remove percieved or actual benefits of a community, because, if anything - you'd be infringing on their privilege to get a better product on account of the collected data.

> I should really stop telling people on the internet that they are wrong, It's gonna save me a lot of time for other activities. The extreme views expressed in this post are mine and mine alone. I am not affiliated with netdata in any other way than being an open source contributor, nor do my views explicitly represent them in any way, shape or form.

**Comment by cakrit** [comment]
Related issues: #7401, #7402, #7403, #7404, #7405

**Comment by sneak** [comment]
>  I personally see absolutely no harm to anyone from maintaining an opt-out mechanism from anonymous statistics.

Here's one: @titpetric has created an image:

https://github.com/titpetric/netdata/pull/91

That Caprover has embedded:

https://github.com/caprover/caprover/issues/553

Neither one of these downstreams provides any mechanism for notification or opt out.  Your defaults (which you defend as sane, when in reality they are *enabling violation of human rights*) became the only method, and caused my computer to silently spy on my activity for Google, without me ever having an opportunity to object, or even being made aware.

Your defaults matter.  Your ignoring the user's lack of consent is a problem.  It makes your software **spyware**, by definition.  You must *ask for consent*, you cannot assume it.  (Imagine if you assumed consent in other social situations and proceeded as if you already affirmatively obtained it!  It is no different here.)

If you continue to willfully ship spyware, do not be surprised when you obtain publicity for being the kind of people who are fine with shipping spyware.

**Comment by ilyam8** [comment]
It is not full definition from Wikipedia and why Wikipedia definition btw?

**Comment by LionNatsu** [comment]
The point is, when there's no enough notice of telemetry during using it, people will think it is a local program without telemetry but it is not.

As long as telemetry is still not a widely welcomed function, it *must* ask users for an agreement or inform users before fully automated installation. This will also help users from critical infrastructure to not to expose their sensitive information to anyone including ISPs. And it *should* at least enable telemetry as opt-out function, so those users will be able to use it under their security considerations.

However, obviously, it's not an obligation to provide disabled-by-default telemetry software if users have been sufficiently informed. It will be more like a moral or user experience debate, and that will be off-topic from this particular issue.

**Comment by cakrit** [comment]
Two of the linked issues have been closed, changes still pending on the website, docker and k8s.

**Comment by cakrit** [comment]
Just a reminder that the website change is still pending. We have started a project that includes the following change to it (ETA end of Feb):

```
The One-line installation section on the homepage needs to be expanded with additional options.

Instead of a single dropdown, we need the following options:
- Operating System Selection
- Automatic updates: on/off
- Stable/nightly updates
- Anonymous statistics: on/off

Selecting the options should generate the correct command (kickstart.sh or kickstart-static64.sh), 
with the appropriate (up to 3) options. ```

**Comment by sneak** [comment]
Note that calling these “anonymous statistics” is a lie. Google Analytics receives your IP address when reporting them, which is PII.

**Comment by prologic** [comment]
> Just a reminder that the website change is still pending. We have started a project that includes the following change to it (ETA end of Feb):
> 
> ```
> The One-line installation section on the homepage needs to be expanded with additional options.
> 
> Instead of a single dropdown, we need the following options:
> - Operating System Selection
> - Automatic updates: on/off
> - Stable/nightly updates
> - Anonymous statistics: on/off
> 
> Selecting the options should generate the correct command (kickstart.sh or kickstart-static64.sh), 
> with the appropriate (up to 3) options. ```
> ```

@joelhans Can you create an issue for this to update the docs/website? (_if you don't already have one_); Otherwise I can :)
