### ISSUE TITLE
Restructure documentation for each area of Netdata

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#7398]
With #7329 near approval/merging, I wanted to create an issue to track progress on bringing this new structure to each area of Netdata.

## Structure

Every section gets three documents:

`README.md`: Containing a description of the feature, buttons/links to the quickstart, reference guide, and tutorials, a list of tutorials, and a list of related features.
`QUICKSTART.md`: A short how-to guide to enabling and using this feature. For health monitoring, the quickstart helps users find and edit their health config files, and walks through writing a basic health entity.
`REFERENCE.md`: A comprehensive page containing _all_ of the configuration options for the given feature. In this case, the reference guide has all the documentation about health entity syntax, expressions, variables, and so on.

Certain sections, such as collectors, will need other documents on top of these 3, which I will address on a case-by-case basis.

## Roadmap

Here is my roadmap for tackling the project, in the order I'll restructure areas. This is based both on analytics data for what documentation pages are most popular and which are in most need of some restructuring to make them easier to understand.

- [x] Health
- [x] Installation
- [ ] Alarm notifications (in progress)
- [ ] Streaming
- [ ] Daemon + daemon config
- [ ] Web (dashboards, Netdata's dashboards, custom dashboards)

The rest TBD.

**Comment by joelhans** [comment]
Closing this in favor of smaller epics/issues for each overhaul, otherwise this will remain open forever.
