### ISSUE TITLE
Completion of ACLK in agent

### ISSUE THREAD

**Issue by stelfrag** [netdata/netdata#7749]
Description of the high level tasks that need to be completed so by the end of the sprint we will have a fully functional ACLK <-> cloud link

- [ ] Complete the access to the authentication endpoint
- [x] Create the **info** handler response
- [x] Create the **chart** handler response
- [x] Create the **alarms** handler response
- [x] Create the **alarm_log** handler response
- [x] Create the **data** handler response
- [x] Create the **badges.svg** handler response
- [ ] Improve the overall ACLK layer (threads, locking, command queues, certificates etc)
- [ ] Docker file replacement to build and test and new functionality
- [ ] Packaging / installation of the agent with libmosquitto statically linked
- [x] [SPIKE] Integrate libmosquitto / libwebsockets event loops to support wss

**Comment by amoss** [comment]
@thiagoftsm pointed out in another issue that we might need an alarm count as well - can we check during planning if this is necessary?

**Comment by thiagoftsm** [comment]
> @thiagoftsm pointed out in another issue that we might need an alarm count as well - can we check during planning if this is necessary?

What was the final decision about `alarm_count`?

**Comment by amoss** [comment]
Closed in favor of #8279.
