### ISSUE TITLE
Signed Packages

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#7773]
##### Feature idea summary

I ran into this while testing our brand new Binary Packaging build CI?CD flows (_work in progress_) while testing openSUSE packages:

```sh
netdata-0.1-1.x86_64.rpm:
    Package is not signed!

Abort, retry, ignore? [a/r/i] (a): a
netdata-0.1-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.
```

Not only is it a good idea to signed out packages; but it also good security as it ensures both integrity and authenticity. This is a good thing :)

As each OS / Lunux Distro _may_ have slightly different ways to handle this; this issue will be an EPIC covering the major OS / Linux Distro we support today:

- [ ] Signed Debian/Ubuntu packages (Issue: TBD)
- [x] Signed CentOS/Fedora/RHEL packages (Issue: TBD)
- [x] Signed openSUSE packages (Issue: TBD)

##### Expected behaviour

- We signed and publish signed packages for all supported OS / Linux Distro(s) we support building and publishing packages for in CI?CD.

**Comment by prologic** [comment]
Slightly related #7487

**Comment by Ferroin** [comment]
The actual signing process should be the same for all RPM-based distros, there's only one accepted way for a signed RPM to look.

The problematic part here (other than keeping the signing key secure and everything related to that) is that we'll have to provide signing key packages for each distro which inject our own public keys into the trusted keyring for the package manager, which does vary a bit depending on the higher-level package manager involved.

**Comment by Ferroin** [comment]
Based on doing further digging into #7905, PackageCloud appears to have native support for GPG signing packages as they are uploaded. We probably should take advantage of that.

**Comment by Ferroin** [comment]
Correction, it supports verification on upload, not actual signing. We probably want that though once we get signing figured out.

**Comment by prologic** [comment]
I would fully expect the signing process to occur in our build scripts in CI/CD (_Github Actions_) and we can store our GPG key there in Github Secrets.

**Comment by Ferroin** [comment]
We still have plans to eventually implement this, it’s just not likely to happen any time soon.

**Comment by Ferroin** [comment]
We’re in the process of migrating to new repository hosting infrastructure, and this will be handled as part of that migration.

**Comment by Ferroin** [comment]
With the migration to our new infrastructure for our official RPM packages, those packages are no properly signed.

DEB package signing will be handled separately as part of migrating hosting for those to our new infrastructure.

**Comment by Ferroin** [comment]
Closing this as it is finished.

We’re now signing our RPM packages using standard signing mechanisms, and providing archive signatures on our DEB packages using `debsigs`.
