### ISSUE TITLE
Socket per process

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7886]
##### Feature idea summary
After we start to monitor IO per process, it is also interesting to expand this concept to the other eBPF collector (Network viewer) in development, we expect to have the following features with this collector:

- [x] Charts per process: It won't be visible for while, but internally all the statistic information will be grouped using the PID.
- [x] IP range specified together network mask: We will allow our users to specify in different formats the values for the options `inbound` and `outbound`. [Network format](https://github.com/netdata/netdata/issues/7886#issuecomment-600205239)
- [x] Port and IP needs to accept different separators(spaces and commas): Considering that Netdata allows in different configuration files these two separators, we are bringing both to Network viewer config file, because we are not considering to use simple pattern with it. [Ports format](https://github.com/netdata/netdata/issues/7886#issuecomment-600209288)
- [x] Ports for UDP and TCP as different options: Instead to have only one option in the configuration file to specify ports, we will separate them in two different options `destination_tcp_ports` and `destination_udp_ports`. [Ports format](https://github.com/netdata/netdata/issues/7886#issuecomment-600209288)
- [x] Charts with global socket information and not only the specified sockets: This chart will demonstrate the calls for specific functions inside the kernel.
- [x] Use hash tables instead perf events: Perf events needs a lot of CPU usage to transfer data from kernel ring to user ring, instead we will hash tables and read every second the accumulated information stored there. [eBPF docs](https://github.com/netdata/docs/pull/157)
- [x] Is it possible to use eBPF with Kubernetes/Docker: We need to test our collectors inside containers and verify possible options and arguments necessaries to execute them. [Docker](https://github.com/netdata/netdata/issues/7886#issuecomment-600202011)
- [x] How interface in `promiscuous mode` affects the collector: When we set promisc mode on LAN interface, will the collector works normally? Or does the kernel get a different road to publish the packets? [Promisc]( https://github.com/netdata/netdata/issues/7886#issuecomment-599579612 )
- [x] How VLANs impacts the data collection: The same questions made for `promisc` mode are applied here? [VLAN]( https://github.com/netdata/netdata/issues/7886#issuecomment-599607359 )
- [x] Inbound connections: This was never planned for Network Viewer, for while, but considering what is described at https://github.com/netdata/product/issues/525 we will need to consider it in a near future.

##### Expected behavior

- A chart that shows global socket information for TCP and UDP
- Charts that show TCP and UDP information for user-specified IP ranges and ports
- Discussion with the product team about use cases
- Detailed information in this issue how each test was executed.

**Comment by thiagoftsm** [comment]
To confirm that `promiscuous mode` does not affect the eBPF collectors I accessed the url https://www.netdata.cloud/ using Firefox with private window to disable cache. Firstly I open the page without to set `promiscuous mode`, when the page was loaded, I closed the window and I ran the following command:

```
# ifconfig wlan0 promisc
```

to confirm that the interface was set as promisc, I ran the following command:

```
bash-5.0# ifconfig | grep PROMIS
wlan0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
```

finally I executed the steps to load the page again and I compared both charts to confirm that the download of the page was registered and I got the same result.
I also kept the promisc mode on during few hours and I accessed different sites to monitor that the collector was creating peaks when these access happened.

**Comment by thiagoftsm** [comment]
To set a VLAN on Linux I used the following script:

```
vconfig add wlan0 200
ifconfig wlan0.200 192.168.1.200 netmask 255.255.255.0 up

echo 1 > /proc/sys/net/ipv4/ip_forward

ipt="/usr/sbin/iptables"
WAN_IFACE="wlan0"
LAN_IFACE="wlan0.200"
WAN_IP="192.168.0.12"
$ipt -t nat -A POSTROUTING -o $WAN_IFACE -j SNAT --to-source $WAN_IP
$ipt -t nat -A POSTROUTING -o $WAN_IFACE -j MASQUERADE

$ipt -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
$ipt -A FORWARD -i $WAN_IFACE -o $LAN_IFACE -m state --state ESTABLISHED,RELATED -j ACCEPT

$ipt -A FORWARD -i $LAN_IFACE -o $WAN_IFACE -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
```

After this I started the Virtual Box using `bridge interface` on `wlan0.200`.  After the boot finishes, I ran the following commands inside the VM:

```
ifconfig eth0 192.168.1.201 netmask 255.255.255.0
route add -net default gw 192.168.1.200
echo "nameserver 8.8.8.8" >> /etc/resolve.conf
``` 

Some packages were missed when I was testing in this scenario. This has relationship with the functions called inside the kernel on host instead a possible bug with the collector.

**Comment by thiagoftsm** [comment]
To test the eBPF program on docker, I used the following dockerfile:

```
FROM centos:8.1.1911 AS build

RUN yum install -y unzip

ADD . /artifacts

CMD ["/bin/bash"]
```

together the https://github.com/netdata/kernel-collector/suites/527521572/artifacts/3027702 .

To build the image and run commands inside the container, it was used the next command:

```
# docker build -f Docker.ebpf -t kernel-collector:ebpf ./ && docker run -it --privileged -v "$PWD" -v /sys/kernel/debug:/sys/kernel/debug:rw -v /sys/kernel/tracing/:/sys/kernel/tracing/:rw kernel-collector:ebpf /bin/sh
```

When we are inside the docker image, it is necessary to run the next commands before to run the collectors or the tester:

```
# unzip artifacts-glibc_centos8.zip
# tar -xf netdata_ebpf-4_18_0-glibc.tar.xz 
# mv usr/lib64/libbpf_kernel.so /usr/lib64/
# ln -s /usr/lib64/libbpf_kernel.so /usr/lib64/libbpf_kernel.so.0
# ./process_monitor
```

Please, pay attention that all the commands outside and inside docker were ran as `root`.

It is important to say that I did not test scenarios where bare metal and container does not have `KPROBES` or `bpf()` syscall disabled, but for this case the eBPF programs won't run. This conclusion is based in previous tests using VirtualBox and local machine without `KPROBE`.

About the volumes, it is important to notice that we need to pass `rw` in the arguments to be sure that we will have conditions to write in these file systems.

The most important thing in these results it is  the fact that all probes were attached to the kernel inside image instead the bare metal.

[TOP](https://github.com/netdata/netdata/issues/7886#issue-556582294)

**Comment by thiagoftsm** [comment]
As described previously we will allow our users to set the pair `IP` and `MASK` in three different formats:

```
outbound = 10.0.0.0/8 172.16.0.0-255.240.0.0 192.168.0.0/255.255.0.0
inbound = 0.0.0.0/0
```
in these format the value in front the separator will always be the  network address and the second the network mask.

[TOP](https://github.com/netdata/netdata/issues/7886#issue-556582294)

**Comment by thiagoftsm** [comment]
Users can have different `TCP` and `UDP` ports to monitor, with this in mind we are creating two options inside `network_viewer.conf`:

```
destination_tcp_ports = 80,443 19999
destination_udp_ports = 53,123
```

As you can se we are also enabled as separators either  commas or spaces.

[TOP](https://github.com/netdata/netdata/issues/7886#issue-556582294)
