### ISSUE TITLE
health monitoring enhancements

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#809]
- [x] basic rendering of alarms on the dashboard.
- [x] allow alarms to repeat notifications #2956 **top priority**
- [x] Silencing alarms/maintenance periods #2673, #3187 
- [ ] render all alarm data on the dashboard and allow users to view health configuration per chart, including the available variables. #4941 
- [ ] central monitoring: allow alarms to be propagated to a central netdata server, which will send all notifications. The central monitoring server should also be able to detect when netdata servers are restarted, or netdata servers are unreachable. #1527 
- [ ] allow propagating the alarms to third party NMS systems. Currently, this can only be done by setting the `exec` line on alarms and templates. However, only one such line is allowed. We could have a solution that allows multiple scripts to handle the same alarm. 
- [ ] implement an alarm flood protection system. #1663
- [ ] allow variables in the `family` index in the form `context.variable`. This is useful in cases where an alarm template needs to refer to another alarm that overlaps with a dimension, so it is not directly exposed in the `family` index. #4154 
- [ ] allow charts to have tags and alarm templates to examine these tags. This would allow disk space alarm templates to be applied on disks with a specific mount point, or fstype, etc. #(https://github.com/firehol/netdata/issues/1231#issuecomment-267164281) -> #4986, #3813 
- [x] Rich notifications #2351, #946 
- [ ] More integrations #2720, #3774, #3997, #3788
- [x] Make alarm-notify.sh modular #3963 
- [ ] Better alarms and alarm handling #4727, #4313, #2477, #1663
- [ ] USE and RED methods checklist #4313

**Comment by davidak** [comment]
one should be able to acknowledge warning/critical states, so it don't send alerts. the acknowledgement get's deleted if it recovers.

nice would be an option to acknowledge the current value (97% disk usage is OK, but alert again for >= 98%)!

optionally comment acknowledgement
optionally send alert/mail for adding an acknowledgement (with comment)
optionally set expire date/time or timespan like `30m` or `1h 30m` or `2d`

this is how it looks in Icinga Web 1:
<img width="590" alt="bildschirmfoto 2016-09-01 um 20 49 14" src="https://cloud.githubusercontent.com/assets/91113/18180256/538c456a-7086-11e6-80c3-f7233ed4fc56.png">

**Comment by ktsaou** [comment]
this is nice, but it is to be done after roles, authentication, etc.

**Comment by rasmusdencker** [comment]
Just wanted to chime in on this one; these ideas goes on top of what @davidak wrote.

### 1 Acknowledgement state
Maybe we should be able to control a state on the acknowledgement, maybe to a fixed set as a start, optionally configurable in the future. States could be represented by an integer, something like `investigating (1)`, `solved (2)` and `ignored (2)`. These could later on be used in expressions other places in the alarm, fx. `$ackState > 1`

### 2A Alarm escalation policies
The ability to define a line-of-command with recipient roles.  Fx dev => sysadmin => l33ts.
When the alarm is triggered, it is sent to the `dev` role. Then, if the alarm is not acknowledged within fx 10 minutes, it gets escalated to `sysadmin`. Same thing applies here, if a sysadm does not acknowledge within *n* minutes, the `l33ts` role gets notified. Subsequent notifications goes to the l33ts group, and when the alarm is cleared, it resets the escalation policy and starts with the dev role again.

### 2B Time-based escalation policies
The ability to control in which time slots each escalation policy is applicable. This could be a crontab-syntax, or something a bit more advanced like the [nagios timeperiod definitions](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/objectdefinitions.html#timeperiod). In normal working hours, some Slack channel with all sysadms would be notified first, whereas outside normal working hours and in weekends, someone could get a push notification / SMS (basically just hooking into the current alarm system)

**Comment by pataquets** [comment]
I would like to add, that some features could be better and easily accomplished by just sending/aggregating the alerts into a central server and later using a incident notification/escalation/routing tool or service such as PagerDuty or alike.
NetData is very good at what it does and some of the alert management workflow steps might fall outside its scope, IMO. NetData responsibility should be measuring, displaying and having sensible/knowledgeable/manageable alert thresholds and propagate them where needed. But once an incident is declared, routing can (should?) be done by an external service.
Just my 2c.

**Comment by ktsaou** [comment]
This is on our roadmap.

**Comment by prologic** [comment]
@cakrit This has been opened for over 4yrs and 2yrs with @Ferroin assigned to it. This clutters up our ability so focus on the important stuff. Is this issue still relevant? Can we split this out into relevant product issues (_if not already_)? Thanks!

**Comment by cakrit** [comment]
Indeed. We're rolling out alarm notifications on the cloud very soon and will focus on adding integrations, not routing and escalation policies.
