### ISSUE TITLE
Overall cleanup of the exporting engine

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#8461]
About 30 minor things to implement or to think about. Draft list:

__To implement__
- [x] TLS support in the simple connector worker. OpenTSDB. ( PR #9068 )
- [x] Send anonymous stats for backends and exporting connectors ( PR #9125 )
- [x] Add an alarm to inform users that backends subsystem is deprecated ( PR #9075 )
- [x] Check return values for uv_mutex_init() and uv_cond_init() ( PR #9034 )
- [x] Check if splitting a buffer doesn’t cut '\n' from the output of the Kinesis connector. ( PR #9122 )
- [x] OpenTSDB - revise formatting/sending of HTTP headers ( Go to [description](https://github.com/netdata/netdata/issues/8461#issuecomment-629578886) )
- [x] Move nc-backend.sh (a simple backend database proxy)  ( PR #9030 )
- [x] Add error message: "stream name is a mandatory Kinesis parameter but it is not configured" ( PR #9048 )
- [x] Align update intervals for every instance based on database update interval, print a warning message ( PR #9131 )
- [x] Define alarms using templates ( PR #9075 )

__To create issues__
- [x] HTTP headers in the OpenTSDB connector
- [x] Test read_exporting_config, exporting_select_type
- [x] Check indexes for two instances in unit tests
- [x] Implement http endpoint in destination URL.
- [x] Delete backends after a transition period. host tags are used in rrd_init(). We should delete them after removing backends. (#7017)

__Done__
- [x] Rename fix_... in graphite connector. sanitize?
- [x] Deduplicate fix_graphite_label_key and fix_graphite_label_value
- [x] Write tests for label formatting (escape_json, fix_graphite_label_key, fix_graphite_label_value)
- [x] Implement buffer on failures for simple connection worker
- [x] Unit test for the instance initializer. Can I add JSON there?
- [x] Unit tests for instance initializer should be expanded after the connector structure was removed. I can also add NULLs. An example - test_aws_kinesis_init.

__Won't be implemented__
- [x] ~~Copy the old configuration to a new file~~
- [x] ~~Kinesis configuration can be read in `aws_kinesis.c` then specific_config structure could reside in `aws_kinesis.h`~~
- [x] ~~Default timeout, check the range of connection timeout for simple connector worker~~
- [x] ~~Initialize empty values for configuration options? The same for Prometheus remote write.~~
- [x] ~~Does Prometheus remote write has a default port? Should I add It to the connector specific config?~~
- [x] ~~We can read data from the database using a separate thread for every instance. Would it be faster than using only one thread? That what I was trying to avoid - a separate traversal over all hosts, charts, and dimensions for every instance.~~
- [x] ~~Instead of skipping instance creation in read_config free structures in init_connectors~~
- [x] ~~Expand mock structures and do more checks. It can take a lot of time to change existing tests. I can do it gradually or even create another set of fixtures for two connectors and two instances for each connector. It could be another(separate) test for multiple connectors/instances.~~
- [x] ~~Support TLS in Prometheus remote write. A new issue. Low priority. Doesn't make sense to implement if nobody has voted for it.~~
- [x] ~~Implement a possibility to use different formats for a single connector. For example: - http connector can send json, plaintext, htts, etc.~~

**Comment by marcomusso** [comment]
Just my 2c since I see a couple of points about tags/labels: in another issue/question I suggested to be able to add host tags as labels especially when exporting to Prometheus. It's not a clean up but more of a new feature but just in case... please consider it :)

**Comment by thiagoftsm** [comment]
Thank you for your suggestion @marcomusso !

**Comment by thiagoftsm** [comment]
After tests with OpenTSDB and InfluxDB, it was possible to confirm that the current Header format is not impacting a system when it is running with 1600 metrics.

Return [Top](https://github.com/netdata/netdata/issues/8461#issue-586226714)

**Comment by vlvkobal** [comment]
We should define alarms for the exporting engine and use templates as far as we have a set of charts for every instance.

**Comment by thiagoftsm** [comment]
> We should define alarms for the exporting engine and use templates as far as we have a set of charts for every instance.

I will create alarms for exporting engine in the same PR that I will create alarms for the backend.

**Comment by vlvkobal** [comment]
> Support TLS in Prometheus remote write. A new issue. Low priority. It doesn't make sense to implement if nobody has voted for it.

We won't even create an issue for this. Let users make a feature request if they need it.

**Comment by vlvkobal** [comment]
> Implement a possibility to use different formats for a single connector. For example: - http connector can send json, plaintext, https, etc.

Do we need to set a reminder in a new issue? We can design it when the time comes.

**Comment by thiagoftsm** [comment]
> Do we need to set a reminder in a new issue? We can design it when the time comes.

I agree with you, right now it is not necessary, so we can postpone this.
