### ISSUE TITLE
This agent was built without the dependencies for Cloud and cannot be claimed

### ISSUE THREAD

**Issue by prologic** [netdata/netdata#9239]
If you are seeing the following error message:

> This agent was built without the dependencies for Cloud and cannot be claimed

Please note that specific issues that affect your specifc system:

- [ ] macOS (_via [Homebrew](https://brew.sh)_) => https://github.com/netdata/netdata/issues/9061
- [x] Amazon Linux 2 (_on [EC2](https://aws.amazon.com/ec2/)_) => https://github.com/netdata/netdata/issues/9169
- [x] CentOS 6.x => https://github.com/netdata/netdata/issues/9152
- [X] #8966 -> PR #9263  - if netdata installed with `kickstart-static64.sh` then ACLK cannot connect *(certificate verification failure)* on RHEL like OSs
- [ ] FreeBSD => https://github.com/netdata/netdata/issues/9109

@netdata/agent Please add additional issues for other specific systems the ACLK either does not work correctly (_for whatever reason_) or the Netdata installer does not correctly support.

**Comment by prologic** [comment]
cc @zack-shoylev @Ferroin

**Comment by amoss** [comment]
This issue in the default CentOS 8 config may affect more distros.

https://github.com/netdata/netdata/issues/8966#issuecomment-636676683

**Comment by underhood** [comment]
For CentOS6 there was patch merged recently (1ac12904b0697f1a3131af2f9ed3addc6b396ad9). I am able to connect and claim my CentOS6 node after that patch.

**Comment by prologic** [comment]
> For CentOS6 there was patch merged recently ([1ac1290](https://github.com/netdata/netdata/commit/1ac12904b0697f1a3131af2f9ed3addc6b396ad9)). I am able to connect and claim my CentOS6 node after that patch.

I saw. :) Does this properly close out #9152? If so I will close it as such.

**Comment by underhood** [comment]
Well it fixes some cases of CentOS6 ACLK build failures .Hard to tell what exactly broke in case of #9152 as there is not much info to go by. But probably yes. I am closing it. Worst case Zack will reopen it and i will query more info

**Comment by underhood** [comment]
@prologic please wait with closing that issue. I will retest. Additionally, it seems so that we have a problem with `kickstart-static64` on some systems (CentOS8). So CentOS6 might be affected by both actually (1ac1290 one and one I just mentioned as well)

**Comment by underhood** [comment]
OK so issue here is only with static install with `kickstart-static64`. Other methods work on the same OS.

The reason seems to be that in static install we include static build of openssl in the executable. That executable together with openss library is build on Alpine Linux. Alpine linux and some RHEL like distros (example CentOS) have incompatible paths for certificates. openssl config file etc.

Therefore we cannot take `openssl` built on Alpine Linux and use it on CentOS.

Now how to solve this... ideas? @amoss @Ferroin

**Comment by underhood** [comment]
@amoss I am able to look into all of those except MacOS failures

**Comment by prologic** [comment]
> @amoss I am able to look into all of those except MacOS failures

macOS has known issues that I have in my Backlog, but other things are getting in the way.

**Comment by jurgenhaas** [comment]
I'm seeing this on Ubuntu 18.04 - in my local network I have 3 hosts with similar setup and all 3 got installed through git clone and using the installer script. One of the 3 works ok, the other 2 respond with `This agent was built without the dependencies for Cloud and cannot be claimed` - not sure what's the difference though.

**Comment by amoss** [comment]
> I'm seeing this on Ubuntu 18.04 - in my local network I have 3 hosts with similar setup and all 3 got installed through git clone and using the installer script. One of the 3 works ok, the other 2 respond with `This agent was built without the dependencies for Cloud and cannot be claimed` - not sure what's the difference though.

Can we take a look at the `config.log` from one of the 2 installs that report a problem? It will show us which of the dependencies failed to build.

**Comment by jurgenhaas** [comment]
Where would I find that config.log? It isn't in the current directory and it's not in /var/log/netdata

**Comment by ilyam8** [comment]
@jurgenhaas in the source code dir

**Comment by jurgenhaas** [comment]
Here you go. It contains a lot of string `error` but with my knowledge I wasn't able to identify which one could be the cause of the problem:

[config.log](https://github.com/netdata/netdata/files/4729565/config.log)

**Comment by amoss** [comment]
Lots of errors is normal - the automake / autotools is a big bag of heuristics that try different compilations to see what works and what fails, this builds up a profile of your system that is used to configure the netdata compilation. It looks like two of the dependencies failed to build - json-c and libwebsockets.
```
configure:8323: checking if statically built json-c is present
configure:8356: result: no
configure:8371: checking if json-c should be used
configure:8381: result: no
...
configure:8962: checking if cloud functionality should be enabled
configure:8964: result: detect
configure:8977: checking if libmosquitto static lib is present (and builds)
configure:8990: gcc -o conftest -O2 -pthread   conftest.c externaldeps/mosquitto/libmosquitto.a -lcrypto -lssl >&5
configure:8990: $? = 0
configure:9004: result: yes
configure:9007: checking if libwebsockets static lib is present
configure:9018: result: no
configure:9031: checking if json-c available for ACLK
configure:9033: result: no
configure:9039: checking if netdata agent-cloud-link can be enabled
configure:9046: result: no
configure:9052: checking if netdata agent-cloud-link should/will be enabled
configure:9067: result: no
```
When you run the installer it generates a lot of output, but among that output do you see any errors?

**Comment by jurgenhaas** [comment]
I only saw the errors in the attached config.log above - during installation I don't see any because I always deploy with Ansible. Do you know which libraries or packages I should install on the host in order to provide json-c and libwebsockets?

**Comment by jurgenhaas** [comment]
I have installed `libjson-c-dev` and `libwebsockets-dev` and re-installed netdata, but the problem remains the same.

**Comment by jurgenhaas** [comment]
Ansible is just a provisioning tool and logging is configurable. For proven processes I tend to minimize log output as it is not helpful normally.

I have now called the install script manually and saw, that cmake was missing. Installed that too and now registration works just fine.

**Comment by amoss** [comment]
Oh yes - that is required for the libwebsockets build. Happy to hear that it is working.

**Comment by amoss** [comment]
I think this is possible - @Ferroin is there an option for this in the installer?

**Comment by prologic** [comment]
> I think this is possible - @Ferroin is there an option for this in the installer?

Be sure to use @netdata/infra as it tags the whole team :)

To answer your question; no not really (_sort or / kind of / but not really_). Our installer _does_ support "offline installs" but it really needs a lot of love to make it easier for our users.

Supporting installation of Netdata whtini mainland China is also a KP and tracked by #9138

**Comment by stefano-cherchi** [comment]
My NetData cloud worked flawlessly for weeks on Ubuntu 18.04 until today, when I updated it by running `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)` as I did many times before. 

From that moment on, the web dashboard started throwing an error: 

`"Installation error , The installer could not prepare the required dependencies to enable Netdata Cloud Functionality" `

and when I try to re-claim the nodes the command line throws

`This agent was built without the dependencies for Cloud and cannot be claimed`

**Comment by ilyam8** [comment]
> as I did many times before.

When was the last time? It is not really clear what your version was before the update.

**Comment by underhood** [comment]
@stefano-cherchi is it possible to get the output of the installer? It is quite long but it should say what failed.

**Comment by amoss** [comment]
@stefano-cherchi I can replicate your problem here in Vagrant. I will give the Vagrantfile to the team and get them to take a look at it.

@agent-sre How do I extract the `config.log` from a system that was installed using `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)` ?

**Comment by amoss** [comment]
@prologic / @Ferroin : I hacked the script to get the `.run` blob out and realised that there is no log for me to extract. Could you take a look at the build that produced the blob and work out which dependency is missing and why?

**Comment by underhood** [comment]
@agent-sre Can we persist the installer output in case of failure? This way when some users report issues we can see what failed.

**Comment by stefano-cherchi** [comment]
> 
> 
> @stefano-cherchi is it possible to get the output of the installer? It is quite long but it should say what failed.

Here it is:
```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)
 --- Downloading static netdata binary: https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run ---
[/tmp/netdata-kickstart-Sxno0n]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-Sxno0n/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt
 OK

[/tmp/netdata-kickstart-Sxno0n]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-Sxno0n/netdata-latest.gz.run https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run
 OK

 --- Installing netdata ---
[/tmp/netdata-kickstart-Sxno0n]# sh /tmp/netdata-kickstart-Sxno0n/netdata-latest.gz.run -- --auto-update

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  (C) Copyright 2017, Costa Tsaousis
  All rights reserved
  Released under GPL v3+

  You are about to install netdata to this system.
  netdata will be installed at:

                    /opt/netdata

  The following changes will be made to your system:

  # USERS / GROUPS
  User 'netdata' and group 'netdata' will be added, if not present.

  # LOGROTATE
  This file will be installed if logrotate is present.

   - /etc/logrotate.d/netdata

  # SYSTEM INIT
  This file will be installed if this system runs with systemd:

   - /lib/systemd/system/netdata.service

   or, for older Centos, Debian/Ubuntu or OpenRC Gentoo:

   - /etc/init.d/netdata         will be created


  This package can also update a netdata installation that has been
  created with another version of it.

  Your netdata configuration will be retained.
  After installation, netdata will be (re-)started.

  netdata re-distributes a lot of open source software components.
  Check its full license at:
  https://github.com/netdata/netdata/blob/master/LICENSE.md
Please type y to accept, n otherwise: y
Creating directory /opt/netdata
Verifying archive integrity...  100%   All good.
Uncompressing netdata, the real-time performance and health monitoring system  100%
 --- Attempt to create user/group netdata/netadata ---
Group 'netdata' already exists.
User 'netdata' already exists.
 --- Add user netdata to required user groups ---
Group 'docker' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'nginx' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'varnish' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'haproxy' does not exist.
 FAILED  Failed to add netdata user to secondary groups

User 'netdata' is already in group 'adm'.
Group 'nsd' does not exist.
 FAILED  Failed to add netdata user to secondary groups

User 'netdata' is already in group 'proxy'.
Group 'squid' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'ceph' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'nobody' does not exist.
 FAILED  Failed to add netdata user to secondary groups

Group 'I2C' does not exist.
 FAILED  Failed to add netdata user to secondary groups

 --- Check SSL certificates paths ---
 --- Install logrotate configuration for netdata ---
[/opt/netdata]# chmod 644 /etc/logrotate.d/netdata
 OK

 --- Telemetry configuration ---
You can opt out from anonymous statistics via the --disable-telemetry option, or by creating an empty file /opt/netdata/etc/netdata/.opt-out-from-anonymous-statistics

 --- Install netdata at system init ---
Installing systemd service...
[/opt/netdata]# cp system/netdata.service /lib/systemd/system/netdata.service
 OK

[/opt/netdata]# systemctl daemon-reload
 OK

[/opt/netdata]# systemctl enable netdata
 OK

 --- Install (but not enable) netdata updater tool ---
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool ---
Adding to cron
Auto-updating has been enabled. Updater script linked to: /etc/cron.daily/netdata-updater

netdata-updater.sh works from cron. It will trigger an email from cron
only if it fails (it should not print anything when it can update netdata).

 --- creating quick links ---
[/opt/netdata]# rm sbin
 OK

[/opt/netdata]# ln -s bin sbin
 OK

[/opt/netdata/usr]# rm bin
 OK

[/opt/netdata/usr]# ln -s ../bin bin
 OK

[/opt/netdata/usr]# rm sbin
 OK

[/opt/netdata/usr]# ln -s ../bin sbin
 OK

[/opt/netdata/usr]# rm local
 OK

[/opt/netdata/usr]# ln -s . local
 OK

[/opt/netdata]# rm netdata-configs
 OK

[/opt/netdata]# ln -s etc/netdata netdata-configs
 OK

[/opt/netdata]# rm netdata-web-files
 OK

[/opt/netdata]# ln -s usr/share/netdata/web netdata-web-files
 OK

[/opt/netdata]# rm netdata-plugins
 OK

[/opt/netdata]# ln -s usr/libexec/netdata netdata-plugins
 OK

[/opt/netdata]# rm netdata-dbs
 OK

[/opt/netdata]# ln -s var/lib/netdata netdata-dbs
 OK

[/opt/netdata]# rm netdata-metrics
 OK

[/opt/netdata]# ln -s var/cache/netdata netdata-metrics
 OK

[/opt/netdata]# rm netdata-logs
 OK

[/opt/netdata]# ln -s var/log/netdata netdata-logs
 OK

[/opt/netdata/etc/netdata]# rm orig
 OK

[/opt/netdata/etc/netdata]# ln -s ../../usr/lib/netdata/conf.d orig
 OK

 --- fix permissions ---
[/opt/netdata]# chmod g+rx\,o+rx /opt
 OK

[/opt/netdata]# chown -R netdata:netdata /opt/netdata
 OK

 --- fix plugin permissions ---
[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/apps.plugin
 OK

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/apps.plugin
 OK

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/ioping
 OK

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/ioping
 OK

[/opt/netdata]# chown root:netdata usr/libexec/netdata/plugins.d/cgroup-network
 OK

[/opt/netdata]# chmod 4750 usr/libexec/netdata/plugins.d/cgroup-network
 OK

[/opt/netdata]# chown root:netdata bin/fping
 OK

[/opt/netdata]# chmod 4750 bin/fping
 OK

Configure TLS certificate paths
Using /etc/ssl for TLS configuration and certificates
Save install options
 --- starting netdata ---
 --- Restarting netdata instance ---

Stopping all netdata threads
[/opt/netdata]# stop_all_netdata
 OK

Starting netdata using command 'systemctl start netdata'
[/opt/netdata]# systemctl start netdata
 OK


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata              .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed now!  -'   '-'   '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

[/opt/netdata]# chmod 0644 /opt/netdata/etc/netdata/netdata.conf
 OK

 OK

[/tmp/netdata-kickstart-Sxno0n]# rm /tmp/netdata-kickstart-Sxno0n/netdata-latest.gz.run
 OK

[/tmp/netdata-kickstart-Sxno0n]# rm -rf /tmp/netdata-kickstart-Sxno0n
 OK

```

Apparently, the only "FAILED" tasks are those that add the netdata user to some non-existing groups.

**Comment by prologic** [comment]
@amoss What exactly are you looking for out of the static builds? These currently happen nightly from Travis (_being phased out_) but I put in place Github Workflow CI checks to prevent breakage of the static builds which you can see [here](https://github.com/netdata/netdata/runs/778881641?check_suite_focus=true) that produce output like:

```
Preparing build ...                     [ OK ]
Building static x86_64 ...              [ OK ]
Preparing assets ...                    [ OK ]
🎉 All Done!
```

If you help me understand what you're looking for maybe I can improve the CI check itself. I _can_ also upload the `config.log` or any log files you want from the build process as artefacts for the build checks done via our Github Workflows as well if that is useful.

**Comment by prologic** [comment]
I actually suspect we have a bug in our build scripts that means `can_enable_aclk_POST` has a value of `"no"` in this script:

```#!sh
prologic@Jamess-iMac
Wed Jun 17 13:45:59
~/Netdata/netdata
 (master) 1
$ sift 'This agent was built without the dependencies for Cloud and cannot be claimed'
claim/netdata-claim.sh.in:118:    echo >&2 "This agent was built without the dependencies for Cloud and cannot be claimed"
```

But I really have a dislike for autoconf/autotools and mixing multiple languages/DSLs in a source file so I can't yet find out how this is suppose to work:

```#!sh
prologic@Jamess-iMac
Wed Jun 17 13:46:42
~/Netdata/netdata
 (master) 0
$ sift 'can_enable_aclk'
configure.ac:646:        can_enable_aclk="yes"
configure.ac:648:        can_enable_aclk="no"
configure.ac:650:    AC_MSG_RESULT([${can_enable_aclk}])
configure.ac:652:    test "${enable_cloud}" = "yes" -a "${can_enable_aclk}" = "no" && \
configure.ac:657:        enable_aclk=$can_enable_aclk
configure.ac:661:    AC_SUBST([can_enable_aclk])
build/subst.inc:12:		-e 's#[@]can_enable_aclk_POST@#$(can_enable_aclk)#g' \
claim/netdata-claim.sh.in:117:if [ "@can_enable_aclk_POST@" != "yes" ]; then
```

**Comment by prologic** [comment]
I will test this hypothesis now since fortunately I did put some CI together for this and thus associated shell scripts to make producing/building our Static Netdata easier for anyone:

```#!sh
prologic@Jamess-iMac
Wed Jun 17 13:50:33
~/Netdata/netdata
 (master) 0
Preparing build ...                     [ OK ]
Building dist ...                       [ OK ]
Building static x86_64 ...
...
```

**Comment by prologic** [comment]
Nope I was wrong;

```#!sh
prologic@Jamess-iMac
Wed Jun 17 14:57:15
~/Netdata/netdata
 (master) 0 1
$ ./artifacts/netdata-v1.22.1-297-g13624215.gz.run --tar -xO ./bin/netdata-claim.sh | grep -C 3 'This agent was built without the dependencies for Cloud and cannot be claimed'
fi
# shellcheck disable=SC2050
if [ "yes" != "yes" ]; then
    echo >&2 "This agent was built without the dependencies for Cloud and cannot be claimed"
    exit 3
fi
```

**Comment by amoss** [comment]
Yes @prologic I need to see:
* The output of the configure step (should be captured in the config.log)
* The output of the build step (i.e. what I see on the terminal when I run make)
* Anything the installer would output not captured by the first two cases.

For this specific problem I think the config.log is enough, but for the general case of diagnosing failures in the static build I would need all three.

**Comment by stefano-cherchi** [comment]
Just updated to v1.22.1-294-g79c06c88 and problem solved.

**Comment by prologic** [comment]
> Just updated to v1.22.1-294-g79c06c88 and problem solved.

Yes good. This means the Revert decision was the right one. I know which commits are the culprit ones then. In fact I was actually having problems building against them.

@amoss Leave this with me I'll figure this out if that's okay; I'm quite sure I can figure this out :)

**Comment by prologic** [comment]
I guess I should trust my instincts a bit more :) Turns out I was right. With @Ferroin PR revert reverted (_i.e: #9311 in place_) the build ends up constructing a `claim.sh` script with:

```#!sh
(⎈ |netdata-production:infra)
prologic@Jamess-iMac
Thu Jun 18 10:20:10
~/Netdata/netdata
 (refix_static_netdata_for_cloud) 0
$ ./artifacts/netdata-v1.22.1-300-g3568def3.gz.run --tar -xO ./bin/netdata-claim.sh | grep -C 3 'This agent was built without the dependencies for Cloud and cannot be claimed'
fi
# shellcheck disable=SC2050
if [ "no" != "yes" ]; then
    echo >&2 "This agent was built without the dependencies for Cloud and cannot be claimed"
    exit 3
fi
```

**Comment by prologic** [comment]
And there we go:

```#!sh
prologic@Jamess-iMac
Thu Jun 18 10:43:20
~/Netdata/netdata
 (refix_static_netdata_for_cloud) 0
$ .github/scripts/build-artifacts.sh
Preparing build ...                     [ OK ]
Building dist ...                       [ OK ]
Building static x86_64 ...              [ ERR ]
 LWS_HAVE_PTHREAD_H = 1
 LWS_WITH_CGI = OFF
 LWS_HAVE_OPENSSL_ECDH_H = 1
 LWS_HAVE_SSL_CTX_set1_param =
 LWS_HAVE_RSA_SET0_KEY =
 LWS_WITH_HTTP_PROXY = OFF
 LIBHUBBUB_LIBRARIES =
 PLUGINS =
 LWS_WITH_ACCESS_LOG = OFF
 LWS_WITH_SERVER_STATUS = OFF
 LWS_WITH_LEJP = ON
 LWS_WITH_LEJP_CONF = ON
 LWS_WITH_SMTP = OFF
 LWS_WITH_GENERIC_SESSIONS = OFF
 LWS_STATIC_PIC = OFF
 LWS_WITH_RANGES = OFF
 LWS_PLAT_OPTEE = OFF
 LWS_WITH_ESP32 = OFF
 LWS_WITH_ZIP_FOPS = OFF
 LWS_AVOID_SIGPIPE_IGN = OFF
 LWS_WITH_STATS = OFF
 LWS_WITH_SOCKS5 = ON
 LWS_HAVE_SYS_CAPABILITY_H =
 LWS_HAVE_LIBCAP =
 LWS_WITH_PEER_LIMITS = OFF
 LWS_HAVE_ATOLL = 1
 LWS_HAVE__ATOI64 =
 LWS_HAVE_STAT32I64 =
 LWS_HAS_INTPTR_T = 1
 LWS_WITH_EXPORT_LWSTARGETS = ON
 LWS_WITH_ABSTRACT =
---------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2
 OK

[/tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2]# make
Scanning dependencies of target websockets
[  1%] Building C object CMakeFiles/websockets.dir/lib/core/alloc.c.o
In file included from /tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2/include/libwebsockets.h:576:0,
                 from /tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2/lib/core/private.h:130,
                 from /tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2/lib/core/alloc.c:1:
/tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2/include/libwebsockets/lws-genhash.h:79:18: error: field 'ctx' has incomplete type
         HMAC_CTX ctx;
                  ^~~
make[2]: *** [CMakeFiles/websockets.dir/build.make:63: CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/websockets.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
 FAILED

[/usr/src/netdata.git]# mkdir -p /usr/src/netdata.git/externaldeps/libwebsockets
 OK

[/usr/src/netdata.git]# cp /tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2/lib/libwebsockets.a /usr/src/netdata.git/externaldeps/libwebsockets/libwebsockets.a
cp: can't stat '/tmp/netdata-libwebsockets-CfjeoN/libwebsockets-3.2.2/lib/libwebsockets.a': No such file or directory
 FAILED

 FAILED  Failed to build libwebsockets.


  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues


Build failed.Dropping into a shell for debugging ...
sh: _kube_ps1_update_cache: command not found
sh: _direnv_hook: command not found
sh-3.2$
```

**Comment by prologic** [comment]
This seems to be related to https://github.com/warmcat/libwebsockets/issues/1835

**Comment by prologic** [comment]
Upgrading libwebsockets from v3.2.2 to v3.3.3 has the same problem.

**Comment by prologic** [comment]
And voila!

```#!sh
prologic@Jamess-iMac
Fri Jun 19 17:01:10
~/Netdata/netdata
 (refix_static_netdata_for_cloud) 0
$ .github/scripts/build-artifacts.sh
Preparing build ...                     [ OK ]
Building static x86_64 ...              [ OK ]
Preparing assets ...                    [ OK ]
🎉 All Done!
```

Now to test this new binary...

**Comment by prologic** [comment]
https://github.com/netdata/netdata/pull/9381 finally fixes Netdata Static to finally have full Netdata Cloud support. Tested on Debian 10 and CentOS 7.

**Comment by amoss** [comment]
@prologic I'm not sure how we can close this - it seems to be open-ended. Do you have any ideas?

**Comment by prologic** [comment]
@amoss Yeah it was collecting all related issues here. We can close it I think as we have separate ones now to fix and I've not seen anymore to collect here. Closing...

**Comment by CberYellowstone** [comment]
@prologic now I have the same problem on my `centos7.9` ,and I don't know how to fix this problem
my netdata version is `1.28.0`, and it's installed by rpm from the `packagecloud` source
so is there any bugs not fix yet?
![image](https://user-images.githubusercontent.com/37031767/103450708-06388d00-4cf5-11eb-862e-f8d46ab24010.png)

**Comment by Habetdin** [comment]
Upgraded my `netdata` to `v1.28.0` (I'm using netdata/netdata packagecloud) @ `Ubuntu 18.04` and got same message in the Web UI:

> The installer could not prepare the required dependencies to enable Netdata Cloud functionality

And the next message when I'm trying to use `netdata-claim.sh`:

> This agent was built without the dependencies for Cloud and cannot be claimed

**Comment by Habetdin** [comment]
cc @underhood

_Should me and @CberYellowstone open a new issue for this problem?_

**Comment by CberYellowstone** [comment]
> cc @underhood
> 
> _Should me and @CberYellowstone open a new issue for this problem?_

#10457

**Comment by ariyansbr** [comment]
same problem on `Ubuntu 16.04` and `netdata v1.28.0-96-g53fca84`  when I'm trying to use netdata-claim.sh:


    This agent was built without the dependencies for Cloud and cannot be claimed

**Comment by underhood** [comment]
@ariyansbr in case you installed binary package fix for this is already pending here #10460. Thank you for reporting and in case you used different install method or believe $10460 won't fix it please let me know.

**Comment by maxlklaxl** [comment]
same on `Ubuntu 18.04 ` `netdata v1.28.0`

**Comment by underhood** [comment]
@maxlklaxl what is your install method?

**Comment by CberYellowstone** [comment]
> @maxlklaxl what is your install method?

em, now I have already update my `netdata` to `v1.28.0-181-nightly`,
but the problem still exists
how can i get fix it
@underhood @Ferroin

**Comment by Ferroin** [comment]
@CberYellowstone Can you please post the output of `netdata -W buildinfo` on a system where you are seeing this issue?

**Comment by CberYellowstone** [comment]
> netdata -W buildinfo

here is the output of `netdata -W buildinfo` on my `centos7.9`

> [root@localhost ~]# netdata -W buildinfo
Version: netdata v1.28.0-181-nightly
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-libJudy=externaldeps/libJudy' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           NO
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     NO
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
[root@localhost ~]# 


![image](https://user-images.githubusercontent.com/37031767/105799772-462b2100-5fd0-11eb-81e8-6726e26083e7.png)
